tinacms/tina.io

components/styles/GlobalStyle.tsx

* Fixes unstyled flashing between pages

use memo for globalstyle

---

components/layout/DocsLayout.tsx
components/layout/Layout.tsx
components/layout/RichTextWrapper.tsx
components/styles/GlobalStyle.tsx
components/styles/RichText.tsx
pages/_app.js

* Sets og:url for every page
* Adds meta-theme color
* Reduces (potentially fixes) style flashing between pages 
* Moves globaStyles to the app.js file instead of having it in both layout files.

Post Launch Fixes

---

content/blog/simple-markdown-blog-nextjs.md

Fix 404 on https://tinacms.org/blog/simple-markdown-blog-nextjs

fix: image path

---

components/ui/HeaderNav.tsx

fix search in docs header

---

content/docs/fields/image.md
content/docs/gatsby/inline-editing.md

Hi, I spotted a broken link also in the example I edited the button disappears in edit mode preventing you from exiting back into preview mode.

A couple of minor edits

---

content/blog/custom-field-plugins.md
content/docs/fields/custom-fields.md
content/docs/gatsby/custom-fields.md
utils/blog_helpers.ts

Add field plugin post

---

package.json
yarn.lock

Upgrades Tina packages so that the pages with Tina render in production

Test inline fix

---

content/docs/concepts/sidebar.md

Updates docs for this feat — https://github.com/tinacms/tinacms/pull/769

docs: adds hidden sidebar setter documentation

---

components/layout/EditLink.tsx
next.config.js
open-authoring/prPlugin.js
pages/api/preview.ts
pages/github/fork.tsx
pages/index.tsx

pulls head branch from cookies

---

content/blog/using-tinacms-on-gatsby-cloud.md
content/docs/gatsby/configure-git-plugin.md

This should be merged when https://github.com/tinacms/tinacms/pull/734 is merged

Configure git remote refactor

---

content/docs/fields/html.md
content/docs/fields/number.md
content/toc-doc.json

Documentation for `HtmlFieldPlugin` implemented in tinacms/tinacms#805

docs: add HTML field documentation

---

content/docs/gatsby/configure-git-plugin.md

Documentation for tinacms/tinacms#817

docs: document TINA_GIT_DEBOUNCE_MS

---

content/docs/cms.md

meant to remove this block from the initial revisions PR

remove extraneous docs

---

components/layout/OpenAuthoringSiteForm.tsx
open-authoring/OpenAuthoringModalContainer.tsx
pages/blog/[slug].tsx
pages/community.tsx
pages/docs/[...slug].tsx
pages/index.tsx
pages/teams.tsx

Add inline editing to all tina pages.

Inline site form

---

components/logo/TinaIcon.tsx

Closes #156 
Video of it working:
https://www.loom.com/share/7c9fcc7e57d146ca830638c4f58e89fb

Use next/link for TinaIcon

---

components/layout/EditLink.tsx
open-authoring/OpenAuthoringModalContainer.tsx
open-authoring/authFlow.js

Fix an issue where auth window is blocked by the browser if opened asyncronously

Auth modal blocking fix

---

components/layout/EditLink.tsx
pages/blog/[slug].tsx
pages/blog/page/[page_index].tsx

Right now it sits with the other meta data at the top of the blog. To me this feels more 'in' the site as opposed to the floating UI that feels Tina specific.

Add blog edit icon

---

content/docs/fields/html.md
content/docs/fields/number.md
content/docs/gatsby/configure-git-plugin.md
content/toc-doc.json

[Milestone](https://github.com/tinacms/tinacms/milestone/14?closed=1)

2020 03 02 release docs

---

content/blog/introducing-visual-open-authoring.md

The main thing I did here was reduce the size of the Next.js section. I don't think we need to go into that much detail (maybe a later post) and it starts to take away from the main point.
aside from that it's mostly smoothing language, enforcing good information hierarchy, and driving home this **Visual Open Authoring** term

Revisions to "Introducing Visual Open Authoring"

---

open-authoring/PRModal.tsx
open-authoring/PRPlugin.tsx
open-authoring/github/api/index.js
pages/blog/[slug].tsx
pages/blog/page/[page_index].tsx
pages/community.tsx
pages/docs/[...slug].tsx
pages/index.tsx
pages/teams.tsx
utils/docs/getDocProps.ts
utils/github/getFiles.ts
utils/github/getJsonData.ts
utils/github/getMarkdownData.ts
utils/github/sourceProviderConnection.ts
utils/github/useGithubForm.ts
utils/github/useLocalGithubJsonForm.ts
utils/github/useLocalGithubMarkdownForm.ts
utils/plugins/MarkdownCreatorPlugin.ts

Don't pass access token to front-end

Proxying frontend authtokens

---

components/ui/Video.tsx
pages/index.tsx

Improves performance of editing since the browser isn't always repainting the video

Video doesn't autoPlay in editing mode

---

content/docs/media.md
content/docs/nextjs/adding-backends.md

Add some notes about the `GitMediaStore` to the docs

Git media store

---

components/ui/DocsPagination.tsx

fix docs pagination spacing

---

content/pages/home.json

Fix minor content issues

---

components/ui/Video.tsx

Fixes homepage performance issues in firefox.

switch from filter to box-shadow

---

components/search/hitComps.tsx

fix date formatting in search

---

content/blog/introducing-visual-open-authoring.md

Linked to next.js announcement and added copy about Tina Teams

---

content/blog/introducing-visual-open-authoring.md

This was confusing before because it said "the Tina Team..." (as in, the people behind tina) but in the previous sentence we refer to Tina Teams (the product).

Updated copy 

---

content/blog/creating-markdown-drafts.md

I was looking for a way to handle drafts with TinaCMS and NextJS, and I stumble on this post, but it's based on Gatsby. I renamed the blog post to reflect its content.

Blog: rename post

---

components/layout/MarkdownContent.tsx
content/docs/cms.md
content/docs/cms/alerts.md
content/docs/cms/apis.md
content/docs/cms/plugins.md
content/toc-doc.json
package.json
utils/shortcodes.tsx
yarn.lock

- Breaks out CMS docs into subsections
- adds documentation on alerts
- adds shortcode capability to markdown content

Break out cms docs

---

content/docs/cms.md

Reflect changes from https://github.com/tinacms/tinacms/pull/873

docs: Tina > TinaProvider

---

content/blog/tinacms-ui-whats-next.md

I edited the link in VSCode so a lot of the 'changes' are just prettier changes.

chore: update img link

---

package.json
pages/blog/[slug].tsx
pages/blog/index.tsx
pages/blog/page/[page_index].tsx
pages/community.tsx
pages/docs/[...slug].tsx
pages/docs/index.tsx
pages/index.tsx
pages/teams.tsx
utils/docs/getDocProps.ts
utils/github/sourceProviderConnection.ts
yarn.lock

* Upgrade to next@9.3
* Add types for `getStaticProps` 
* Fix up some usage of `getStaticPaths` and `getStaticProps` from changes in `9.3`
Build is failing on NOW but I don't know why

Upgrade next 9 3

---

content/blog/tinacms-ui-whats-next.md

add link to @tinacms/media PR

---

content/blog/2020-03-16-release-notes.md

https://github.com/tinacms/tinacms/milestone/16?closed=1

2020-03-16 Release Notes

---

open-authoring/error-interpreter/actions.ts
open-authoring/withErrorModal.tsx

Fix for auth popup being blocked on "Log In" clicked

Do the async auth checks when error modal shown

---

README.md
next.config.js
package.json
yarn.lock

Add helpers to test with local tinacms dependencies
@ncphillips @jeffsee55 Created a new PR as the last one was reverted with the reverse-auth-flow commit.

Add helpers to test with local tinacms dependencies

---

content/docs/nextjs/adding-backends.md

* fix outdated link to nextjs.org docs

docs: fix link to nextjs.org custom server

---

content/blog/simple-markdown-blog-nextjs.md

Updates blog to use `getStaticProps` from Next.js 9.3 
Closes #312

Update Next.js blog --> getStaticProps

---

content/docs/cms/styles.md

This adds the new z-index CSS custom properties to the styles docs.

chore: add z-index props to styles doc

---

content/blog/2020-04-06-release-notes.md

2020-04-06 Release Notes

---

content/docs/fields/custom-fields.md

Docs: Removes outdated style helper info on Custom Fields doc

---

content/docs/nextjs/creating-forms.md

Following https://github.com/tinacms/tinacms/pull/1012

Remove useLocalForm refs

---

components/ui/Branching.tsx

* Move test data outside of BranchSwitcherPlugin
* Clear scroll position & filter when closing branch switcher
* Adds 'Create Branch' modal & form

Branch Switching Prototype Improvements

---

.env.example
next.config.js
pages/_app.tsx

changed REPO_FULL_NAME to BASE_REPO_FULL_NAME to work with https://github.com/tinacms/tinacms/pull/1037

Updated env repo name to the new wording

---

.env.example
next.config.js
now.json
pages/_app.tsx

Reverts tinacms/tinacms.org#366

Revert "Updated env repo name to the new wording"

---

content/blog/2020-04-27-release-notes.md

April 27 Release Notes

---

content/docs/cms/ui.md
content/toc-doc.json

For the toolbar and sidebar.
closes #354

Adds Editing UI docs

---

content/docs/nextjs/bootstrapping.md

Changed references to `Tina` in the Tina+NextJS section to `TinaProvider`

For the Context.Provider, use 'TinaProvider' over 'Tina'

---

content/blog/2020-05-04-release-notes.md

2020-05-04 Release Notes

---

content/blog/2020-05-04-release-notes.md

Typo on @jhuggett
Edited with Tina ❤️

fix: s/Jeol/Joel

---

content/blog/2020-05-11-release-notes.md

2020-05-11 Release Notes

---

content/docs/inline-editing/inline-image.md

I just wanted to fix the typo `InlineImagefield` to `InlineImageField`. 
Used the Github authoring thing in the process. 
1. Wow
2. It introduces these other cosmetic changes. Let me know if I need to revert those :)

Update from TinaCMS

---

content/blog/2020-05-19-release-notes.md

Blog: fix link and grammar on latest release post

---

content/blog/2020-05-11-release-notes.md

Fixed spelling mistake in post

Modify; 2020 spelling mistake

---

content/blog/2020-05-25-release-notes.md

May 25th Release Notes

---

content/docs/cms/plugins.md
content/docs/fields/html.md
content/docs/fields/markdown.md

* [Updated examples of dynamically loading and registering plugins](https://tinacms-site-next-git-markdown-plugins.tinacms.now.sh/docs/cms/plugins)
* [Mention that Markdown field must be installed manually](https://tinacms-site-next-git-markdown-plugins.tinacms.now.sh/docs/fields/markdown)
* [Mention that Html field must be installed manually](https://tinacms-site-next-git-markdown-plugins.tinacms.now.sh/docs/fields/html)

Markdown plugins

---

content/docs/inline-editing.md
content/docs/inline-editing/inline-image.md
content/docs/inline-editing/inline-text.md
content/docs/inline-editing/inline-textarea.md
content/docs/inline-editing/inline-wysiwyg.md

Remove references to `useLocalForm`

"inline editing" docs updates

---

content/blog/2020-05-19-release-notes.md

Well, everything is in the title, there was a missing word in the post "time", I clicked "edit this post, forked the site, add the word "time", save the page and did a pull request just to have a taste of this wonderful tinacms github workflow. Now I'm thinking of ways to improve this process for newbies and non-devs, I guess this will be the case for tinaCMS teams; good luck !

missing word in a post (and my first test of tinaCMS, love it!)

---

content/docs/cms.md
content/docs/cms/styles.md

Related to [#1135](https://github.com/tinacms/tinacms/pull/1135)

docs: update dynamic tina styles info

---

content/blog/2020-06-08-release-notes.md

June 8th Release Notes

---

content/blog/2020-06-08-release-notes.md

Awesome release, congrats to the team.
_Edited with Tina 🦙_

fix: typos on release notes

---

components/inline-wysiwyg.tsx
components/layout/OpenAuthoringSiteForm.tsx
package.json
pages/index.tsx
pages/teams.tsx
yarn.lock

updated block templates and other inline editing controls
now demonstrates drag and drop on the home page

upgrade tinacms packages

---

content/docs/fields/toggle.md

toggle field updates

---

content/docs/fields/date.md

- remove gatsby from example
- switch from options list ot table
- add dateFormat and timeFormat to options table

updated date field docs

---

pages/guides/[category]/[guide]/[step].tsx

[Example of a branch with guides having been edited](https://github.com/tinacms/tinacms.org/compare/master...tinacms:editable-guides-tests)
* Edit Guide Step Content
* Edit Guide title and the order of steps
* Create Guide Steps (Adds new page to the navigation)
This PR does not make it possible to create new guides

Editable guides

---

content/guides/nextjs/github-open-authoring/github-oauth-app.md

Updating the "Open Authoring With Github" guide to support the changes made to the auth flow.

Update to guide for new auth flow

---

components/layout/Header.tsx
components/ui/DocsNav.tsx
content/docs/inline-editing/inline-blocks.md

docs: Inline Blocks updated direction & itemProps

---

content/blog/2020-06-23-release-notes.md

Release Notes

---

content/blog/upgrade-notice-improved-github-security.md

Updating the link to the forums to actually link to the post in the forums.

Update Link for blog post

---

next.config.js
package.json
yarn.lock

* reduces bundle size by 428kb
* gives us a visual into the websites bundle
[See this comment for more info on bundle size improvements](https://github.com/tinacms/tinacms/issues/771#issuecomment-646668855)

add webpack plugins for bundle analyzing and moment locale stripping

---

content/guides/nextjs/github-open-authoring/configure-custom-app.md

Updating the enterEditMode function in the open auth guide to work with the new auth flow.

Enter Edit Mode Guide Update

---

content/blog/upgrade-notice-improved-github-security.md

Minor changes: notice about adding key to env vars and reminder about using latest react-tinacms-github version.

Update to blog post

---

content/docs/fields/date.md

Date Field Extraction Docs

---

content/blog/custom-field-plugins.md
content/docs/cms.md
content/docs/cms/ui.md
content/docs/gatsby/manual-setup.md
content/guides/gatsby/adding-tina/project-setup.md
content/guides/nextjs/git-based/adding-backend.md
content/guides/nextjs/git-based/getting-started.md
content/guides/nextjs/github-open-authoring/configure-custom-app.md

Docs for Sidebar/Toolbar Config Changes

---

content/guides/nextjs/github-open-authoring/configure-custom-app.md

Changes for this PR
https://github.com/tinacms/tinacms/pull/1287

Github Auth API Updates

---

content/docs/cms/alerts.md
content/docs/cms/apis.md
content/docs/cms/events.md
content/toc-doc.json

[Check them out here](https://tinacms-site-next-git-events-docs.tinacms.vercel.app/docs/cms/events)

Events Docs

---

content/guides/general/inline-blocks/extend-styles.md

[Need to merge this](https://github.com/tinacms/inline-blocks-demo/pull/1) into the final state branch of the demo when we publish this.

guide: adds block limits example

---

content/guides/nextjs/github-open-authoring/configure-custom-app.md

Fixes unauthorized issue, per https://community.tinacms.org/t/upgrade-notice-improved-github-security/226/6?u=cj

Fixes unauthorized issue

---

utils/getDynamicPath.ts

Fixed the guide links so the page does not refresh on every guide page.

fix: fixed guide links

---

content/blog/upgrade-notice-improved-github-security.md
content/guides/nextjs/github-open-authoring/configure-custom-app.md

onLogin throws errors now for previews

---

content/blog/2020-06-29-release-notes.md

Updating changes noted in #514

Chore: fix cms.toggle example

---

content/docs/cms/events.md

Pending release of https://github.com/tinacms/tinacms/pull/1304

Document github:branch:create event

---

content/docs/inline-editing.md

Remove old Inline controls info

---

content/docs/index.md

Just adding/tweaking some of the "soft" language in the docs index

Docs index suggestions

---

content/docs/cms/events.md

Related to changes from [this PR](https://github.com/tinacms/tinacms/pull/1321)

docs: git:commit event

---

content/docs/inline-editing/inline-image.md

Based on [this question](https://github.com/tinacms/tinacms.org/pull/539) in the forum.

docs: update Inline Gatsby image children example

---

content/docs/nextjs/next-tinacms-github.md

Updating docs with the changes to authentication from the security improvements.

Updating docs for auth changes

---

content/blog/gatsby-tina-101.md
content/blog/screen-plugins.md
content/blog/simple-markdown-blog-nextjs.md
content/blog/three-ways-to-edit-md.md
content/blog/using-tinacms-with-nextjs.md
content/docs/getting-started/introduction.md
content/docs/index.md
content/docs/integrations/gatsby.md
content/docs/integrations/nextjs.md
content/docs/nextjs/next-tinacms-github.md
content/docs/plugins/fields/group-list.md
content/toc-doc.json
now.json

* Added the `content/docs/integrations/` folder
* Added `gatsby.md` and `next.md` files with lots of links to other pages
* Fixed up some links

Docs integrations

---

content/docs/plugins/content-creators.md
content/docs/plugins/forms.md
content/docs/plugins/screens.md

Open to input on the format. I felt those two hooks are the most common ways people will be creating screens but let me know if I left something out.
closes #79

Docs: Screen plugins

---

next.config.js
utils/mailchimp_helper.ts

fix: newsletter signup 

---

content/blog/2020-07-27-release-notes.md

v0.25.0 Release Notes

---

pages/blog/[slug].tsx
pages/docs/[...slug].tsx
pages/guides/[category]/[guide]/[step].tsx

Added last modify to content by using the mtime metadata on files. This may or may not work.

added lastModified to blog, docs, and guides

---

pages/blog/[slug].tsx
pages/docs/[...slug].tsx
pages/guides/[category]/[guide]/[step].tsx

it's not working right and is breaking edit mode

remove "last modified"

---

content/guides/nextjs/adding-tina/next-steps.md

I replaced the "coming soon" part of the guide to a short description + link of the open authoring guide.

Updated the "Saving Content" section in the Tina + Next.js Guide

---

pages/_app.tsx
pages/guides/index.tsx
utils/docs/getPackageProps.ts

this should hopefully fix the file access errors in lambdas

Vercel compat

---

content/blog/upgrade-notice-improved-github-security.md

Fixes a typo on the security post. This is really to see if the last edited piece is working as expected.

Typo on blog post

---

content/guides/nextjs/tina-with-strapi/editing-with-tina.md
content/guides/nextjs/tina-with-strapi/saving-to-strapi.md
content/guides/nextjs/tina-with-strapi/strapi-setup.md

Fixed some typos and spelling. 
Tidied up some diffs & imports.
Had an issue where cover image uploads gave me a 403 so I added a note to check your upload permissions.

Documentation Edits

---

content/guides/nextjs/github/configure-custom-app.md

This PR adds a missing comma to an object within a code block.

Adds Missing Comma To Object

---

components/search/hitComps.tsx
indices/createIndices.ts
utils/blog_helpers.ts

- Adds working excerpt to search results
- Hides excerpts for title hits
- Reduce excerpt generation from 3000 to 200 characters
- Strip markdown from excerpts
- Improve hit components
Todo: fix issue with out of date index data (@dwalkr  is on it)

Improve Nav Search

---

content/docs/plugins/fields.md
content/docs/ui/inline-editing.md

We don't always explain home a field's name works. The final-form docs have a good description.

Link to final-form name docs

---

utils/getDynamicPath.ts

It was annoying me that the page had to refresh every time I was clicking on a new package page so I fixed it.

added packages to dynamic paths

---

components/DocumentationNavigation/DocsHeaderNav.tsx
components/search/hitComps.tsx
components/search/indices.tsx
components/ui/HeaderNav.tsx
data-api/fetchGuides.ts

Add guides to search

---

now.json

Reported on https://github.com/kendallstrautman/quercus-blocks/issues/24

fix: redirects

---

content/docs/media.md

/docs/media links to /packages/react-tinacms-github

---

components/DocumentationNavigation/DocsNavigationList.tsx
components/DocumentationNavigation/DocumentationNavigation.tsx
components/DocumentationNavigation/NavSection.tsx
components/DocumentationNavigation/index.tsx
components/layout/DocsLayout.tsx
pages/guides/[category]/[guide]/[step].tsx

Adds guide breadcrumb

---

content/docs/plugins.md

Link to blog posts on plugins from the /docs/plugins page

Plugins Links

---

pages/rss.xml.tsx
utils/blog_helpers.ts

https://tinacms-site-next-git-fix-rss-feed.tinacms.vercel.app/rss.xml
closes #657

Fix rss feed

---

pages/blog/page/[page_index].tsx
pages/docs/[...slug].tsx
pages/docs/index.tsx
pages/packages/[slug].tsx
pages/packages/index.tsx
utils/getMarkdownPreviewProps.ts

frontend was expecting the "error" not "previewError"

fix error handling on backend.

---

content/docs/ui/inline-editing/inline-text.md
content/docs/ui/inline-editing/inline-textarea.md

Docs updates for tinacms/tinacms#1391

InlineText Updates

---

content/docs/getting-started/backends.md
content/docs/getting-started/cms-set-up.md
content/docs/getting-started/edit-content.md

small fixes for getting started tutorial

---

tinacms/ReleaseNotesCreator.ts

Saves to doc/releases now instead of blog.

Fixed release notes button

---

components/search/index.tsx

Adds links to the forum and github issues if no results are found in search.

chore: link to forum and gh issues in no results

---

content/guides/nextjs/git/getting-started.md

Fixes the link rendering in the toc. 
fixes #673

Toc heading render fix

---

content/docs/index.md
content/docs/plugins/forms.md

Just a few formatting changes and fixed a dead link.

Tiny fixes

---

utils/docs/slugifyToc.test.ts
utils/docs/slugifyToc.ts

fixes slug error on https://tinacms.org/packages/react-tinacms-github

Improve accuracy of slugifyToc

---

components/layout/Layout.tsx
package.json
pages/_app.tsx
pages/docs/[...slug].tsx
utils/docs/getDocProps.ts
utils/error/HTTPError.ts
utils/error/NotFoundError.ts
yarn.lock

Fix release notes creation

---

components/forms/FeedbackForm.tsx
components/toc/index.tsx

Clicking a reaction now triggers the feedback form, making the single required form input selected by the time the submit button is visible.

chore: feedback form reaction required

---

package.json
utils/docs/getPackageProps.ts
utils/docs/slugifyToc.ts
utils/getMarkdownPreviewProps.ts
utils/getTocContent.ts
utils/stripMarkdownLinks.test.ts
yarn.lock

Toc content rework

---

content/docs/events.md

[re: this issue](https://github.com/tinacms/tinacms/issues/1421)

docs: enabled / disabled events to passive tense

---

content/blog/september-update.md
content/docs/media.md

Adds docs for `Media#type` added in tinacms/tinacms#1460

Media#type

---

content/blog/media-update.md

I removed the TODOS but we should toss the version number in a couple places

Media blog revisions

---

content/blog/media-update.md
content/docs/events.md
content/docs/media.md
content/docs/plugins/fields/image.md
content/docs/ui/inline-editing.md

Could use some editing love from everyone 💗!

Media release blog

---

content/docs/ui/inline-editing/inline-blocks.md

From changes in [this PR](https://github.com/tinacms/tinacms/pull/1538)

docs: updates inline block component interface

---

content/guides/gatsby/adding-tina/creating-forms.md

Hello, I just tried the TinaCMS Gatsby Guide and thought that a comma was missing here. I just wanted to open a pull request, if I am right I will be happy about a merge. If not, then I could at least have the nice experience to edit the page inline. Greetings Matthias

Add comma to be valid object

---

content/docs/plugins.md

Docs: plugin typo fix

---

pages/enterprise.tsx
pages/index.tsx

fix: enterprise and home page registers forms

---

content/docs/plugins/fields/toggle.md

Related to new feature from [this PR](https://github.com/tinacms/tinacms/pull/1595)

docs: update custom toggle label field info

---

content/pages/home.json
content/pages/study.json
content/siteConfig.json
pages/index.tsx

Slight copy changes to reflect our focus on Next.js.

Copy: emphase on Next.js

---

content/guides/nextjs/tina-with-strapi/authenticating-with-strapi.md
content/guides/nextjs/tina-with-strapi/front-end-setup.md

Re this [community convo](https://community.tinacms.org/t/media-manager-failed-to-load-media-strapi/389/2)

guides: update strapi media example

---

content/docs/getting-started/backends.md
content/docs/plugins/forms.md

Based on changes in [this PR](https://github.com/tinacms/tinacms/pull/1626).
Closes #752

docs: update useForm loading state info

---

content/docs/ui/inline-editing.md

Fixed typo

---

content/docs/ui/inline-editing/inline-blocks.md

[Related PR.](https://github.com/tinacms/tinacms/pull/1646)

Adds block label to docs

---

content/guides/nextjs/github/configure-custom-app.md

this fixes the buggy appearance of the ToC on https://tina.io/guides/nextjs/github/configure-custom-app/

chore(guides): fix incorrect heading hierarchy

---

content/blog/more-changes-coming-to-inline-editing.md

adds ordinal number to second subheading

fix formatting

---

.github/CODEOWNERS

chore:  add CODEOWNERS

---

content/docs/getting-started/backends.md
content/docs/getting-started/edit-content.md
content/docs/index.md

I was learning about Tina and came across a link that 404'd. I went ahead and [`rg`](https://github.com/BurntSushi/ripgrep)'d the repo to fix similar issues as well.

Fix 404 error

---

content/pages/home.json
content/siteConfig.json

Provide a more descriptive Title and Description for people browsing off-context (SERP, Social Media, Slack, etc.)
note: This feels very nice to be able to edit SEO so easily with Tina ☺️

fix: Homepage SEO

---

content/pages/home.json

updated tag line to remove "ui"

---

content/pages/cloud.json
content/pages/home.json

fixed some spelling errors and grammatical inconsistencies

Spelling error

---

README.md

Reflect new default domain name tinacms.org -> tina.io

docs: tina.io

---

content/docs/ui/inline-editing/inline-image.md

docs: Add documentation on using next/image

---

pages/community.tsx

Quick fix #794
https://tinacms-site-next-git-fix-community-image-tinacms.vercel.app/community/

fix: broken image in production

---

content/pages/home.json

homepage: Jamstack

---

content/docs/plugins/content-creators.md

Fix typo on Content Creators docs

---

content/guides/nextjs/github/github-oauth-app.md

Fix TOC on https://tina.io/guides/nextjs/github/github-oauth-app/

docs: TOC on setting up GitHub OAuth App

---

content/guides/nextjs/github/github-oauth-app.md

The update includes a short edit on the default branch  from 'master' to the newer default 'main'.
Comments: This cause so much trouble while following the tutorial.

Updated default branch

---

content/blog/tina-cloud-a-headless-cms-backed-by-git.md

Revert post to the final state from yesterday

Tina Cloud post updates

---

content/pages/home.json

added banner with Tina Cloud 

---

content/docs/tina-cloud/cli.md
content/docs/tina-cloud/client.md

fix useGraphqlForms typos in client.md

---

content/guides/gatsby/adding-tina/project-setup.md
content/guides/gatsby/git/create-remark-form.md
content/guides/general/inline-blocks/hero-to-block.md

Text shows `yarn dev` while the command used is `yarn develop`.

Minor guides improvements

---

components/styles/DocsRichText.tsx
content/blog/evolution-of-inline-editing.md

Definitely needs some love and polish!

Draft: Evolution of inline editing blog post

---

content/guides/general/inline-blocks/hero-to-block.md

See https://github.com/tinacms/inline-blocks-demo/pull/10 and https://community.tinacms.org/t/modalprovider-and-initialstatus/327

Remove initialStatus as it's obsolete

---

content/blog/tina-cloud-and-nextjs-the-perfect-match.md

@DirtyF I updated it based on @dwalkr comments. I removed some of the stuff about preview mode (as i think it just introduced to much complexity). Didn't want to commit directly so I made a PR. Feel free to merge it if you think it's good.

updated based on comments

---

components/DocumentationNavigation/DocsNavigationList.tsx
content/docs/tina-cloud/cli.md
content/docs/tina-cloud/client.md
content/toc-doc.json
utils/urls.ts

Closes https://github.com/tinacms/tina-cloud-starter/issues/46

Cleanup api docs for Tina Cloud and CLI

---

content/docs/tina-cloud/alpha-faq.md
content/guides/tina-cloud/existing-site/page-preview.md

The referenced Vercel deployment is no longer active

point to tina.io for cloud references

---

content/docs/tina-cloud/client.md

Ready after https://github.com/tinacms/tina-graphql-gateway/pull/191 is merged

added prop docs and example for TinaAuthWall

---

content/blog/meet-james-perkins-our-new-developer-advocate.md

Noticed spelling and grammar after launch

Spelling mistake

---

content/blog/meet-james-perkins-our-new-developer-advocate.md

https://www.youtube.com/c/TinaCMS is much easier to remember 😄

chore: use custom youTube URL

---

content/blog/add-and-delete-files.md
content/blog/creating-markdown-drafts.md
content/blog/editing-on-the-cloud.md
content/blog/exporting-wordpress-content-to-gatsby.md
content/blog/gatsby-tina-101.md
content/blog/inline-editing-project.md
content/blog/introducing-tina-grande.md
content/blog/more-changes-coming-to-inline-editing.md
content/blog/three-ways-to-edit-md.md
content/blog/using-tinacms-on-gatsby-cloud.md

Follow up using the new callout shortcode

Blog: Use new callout shortcode on blog posts

---

content/blog/announcement-tina-cloud-is-officially-in-alpha.md

This is a draft PR for Tina announcement. Working on when to go live etc hence using a Draft PR

Blog post: Tina Cloud is in public Alpha 🎉

---

content/guides/tina-cloud/starter/overview.md

Add Video Tour for the Cloud Starter

Docs: Cloud Starter Video

---

content/pages/home.json

Hero CTA - Cloud Quick Start & Tailwind Sidebar Demo

---

content/blog/announcement-tina-cloud-is-officially-in-alpha.md

This fixed #894 by pushing with a boolean.

Fixes Full Screen issue.

---

content/pages/home.json

Update the section just before the footer and point to our guides to start learning about Tina.

home:  Guides section

---

content/guides/tina-cloud/starter/structure.md

Add Introduction to Tina Cloud GraphQL API video in the cloud starter guide.

docs: add GraphQL video to cloud starter guide

---

content/docs/tina-cloud/dashboard.md

Mainly wanted to explain how the site URL field works, as it's a pretty common tripping point for users.

Add docs around setting up an app

---

content/docs/ui/inline-editing/inline-blocks.md

Ref: https://github.com/tinacms/tinacms.org/commit/374682d02cb307ebfc4baf8a3ab3b8d24bbfc4f3
Discovered by @samueldlay

fix: update broken guide link

---

content/blog/structure-your-content-with-graphql-in-tina.md

I _think_ this should point to altair instead of graphql

Reference altair endoint

---

content/blog/manage-your-media-with-cloudinary.md

Tina Cloud now officially support Cloudinary as a media store 🎉 
👀 [Preview](https://tinacms-site-next-git-cloudinary-blog-post-tinacms.vercel.app/blog/manage-your-media-with-cloudinary/)

Post: Managing Media with Cloudinary 

---

content/guides/experimental/inline-blocks/meta.json
content/guides/gatsby/adding-tina/meta.json
content/guides/gatsby/git/meta.json
content/guides/general/inline-blocks/meta.json
content/guides/nextjs/adding-tina/meta.json
content/guides/nextjs/git/meta.json
content/guides/nextjs/github/meta.json
content/guides/nextjs/tina-with-strapi/meta.json
content/guides/tina-cloud/existing-site/meta.json
content/guides/tina-cloud/starter/meta.json
content/guides/tinacms/getting-started/meta.json
content/toc-doc.json

Sidebar used to highlight the current page but was broken. Updated the links in the sidebar to make it work again 🎉 
Fixes: #934

fix links in sidebar so highlight will work

---

content/docs/tina-cloud/client.md

- Adding introduction
- Adding use cases where needed.

Adding more specifics to the docs:

---

content/docs/index.md

- Include more links.
- More friendly approach.
- Move CTA.

Refreshing the documentation overview page

---

content/guides/tina-cloud/starter/local.md

fix guide typo

---

pages/_app.tsx
pages/docs/[...slug].tsx
pages/guides/[category]/[guide]/[step].tsx
utils/ga/index.js

Added in Google Analytics page view tracking for docs and guides subsections of website.

Add in GA page views for docs/guides

---

content/docs/index.md

Changes the word to control which better reflects Tina.

Changes the world quality to control

---

content/docs/tina-cloud/client.md
content/docs/tina-init-tutorial.md
content/guides/tina-cloud/existing-site/add-tinacms.md
content/guides/tina-cloud/existing-site/create-app.md
content/guides/tina-cloud/starter/connect-to-tina-cloud.md

Remove organization Id refs from docs

Remove org refs

---

content/guides/tina-cloud/starter/structure.md

Adding backticks for correct render.

Adding backticks

---

content/guides/tina-cloud/getting-started/deployment.md
content/guides/tina-cloud/getting-started/overview.md

- Tina Cloud to TinaCMS backend
Forgot these in the merge.

Adding two changes:

---

content/docs/cli-overview.md
content/docs/cli.md
content/docs/schema.md
content/docs/tinacms-reference.md
content/toc-doc.json

Added CLI and Tina init docs. I also changed "Anatomy of the Tina schema" to "content modelling" as I think its a bit easier to understand.

added cli docs

---

content/guides/tina-cloud/getting-started/create-app.md
content/guides/tina-cloud/getting-started/markdown-plugin.md

I added a call out and code block to the first section.
I also cleaned up the markdown plugin section

Two More Changes

---

content/guides/tina-cloud/getting-started/markdown-plugin.md

Adding missing plus

---

content/guides/tina-cloud/getting-started/defining-content.md
content/guides/tina-cloud/getting-started/markdown-plugin.md
content/guides/tina-cloud/getting-started/next-changes.md

Fixes for small wording and grammar issues 

---

content/docs/cli.md

Fixes to CLI docs

---

content/docs/index.md
now.json

Fixes redirect for old cloud links
fixes link in the overview.

fixing a link and adding redirects.

---

content/docs/tina-cloud/alpha-faq.md
content/docs/tina-cloud/beta-migration.md
content/pages/community.json
pages/community.tsx

The current Discord link was expired, I used one that never expires and uses the same one in all places.

fix: Discord link

---

content/docs/tina-cloud/faq.md

Update Discord link in Tina Cloud FAQ page.

Update Discord Link

---

content/docs/graphql.md

Closes https://github.com/tinacms/tinacms.org/issues/978

Add more information on how schema-specific queries are working

---

content/blog/manage-your-media-with-cloudinary.md
content/blog/structure-your-content-with-graphql-in-tina.md
content/blog/using-graphql-with-the-filesystem.md
content/docs/fields/group-list.md
content/docs/graphql.md
content/docs/schema.md
content/docs/tina-cloud/schema-migration.md
content/docs/tina-init-tutorial.md
content/docs/tinacms-context-advanced.md
content/docs/tinacms-context.md
content/guides/tina-cloud/add-tinacms-to-existing-site/content-modelling.md
content/guides/tina-cloud/add-tinacms-to-existing-site/markdown-plugin.md
content/guides/tina-cloud/add-tinacms-to-existing-site/next-changes.md

Took a pretty quick stab at this with find and replace. Sorry for the whitespace diffs
Closes https://github.com/tinacms/tinacms.org/issues/994

Fix naming to singular

---

content/guides/tina-cloud/add-tinacms-to-existing-site/meta.json
content/guides/tina-cloud/add-tinacms-to-existing-site/next-changes.md

I just found the "NextJS Changes" header to be a bit broad. I hope this gives the user a bit of a north star to get through this part of the guide.

docs: Change NextJS guide header

---

content/docs/tina-cloud/faq.md

Fixing a discord link that is expired.

Fix Discord Link

---

content/guides/tina-cloud/add-tinacms-to-existing-site/create-app.md

Removing the stylesheet requirement + @latest

Removing the stylesheet requirement + @latest

---

content/blog/tina-is-in-beta.md

Creating a Draft PR for 👀  feel free to edit the content as you see fit. We are also waiting on Scott's Visionary piece. Not this blog post is already 1200 words. We want to keep it under 5 minutes total, on average it would take someone 4 minutes to read in it's current state.

Tina beta launch post

---

now.json

Oops did the wrong redirect.

---

now.json

Fix #1016 
Redirect /cloud to homepage

fix: 404 on /cloud

---

content/docs/media-cloudinary.md

Removed a bracket that's messing up the link to Cloudinary

Remove unnecessary bracket in docs

---

content/guides/tina-cloud/starter/structure.md
now.json

Fix broken link to schema docs

---

content/blog/tina-cloud-a-headless-cms-backed-by-git.md
content/blog/using-graphql-with-the-filesystem.md

docs: Tina is now in public beta

---

content/docs/advanced-features/custom-fields.md
content/docs/advanced-features/overview.md
content/docs/fields/custom-fields.md
content/docs/schema.md
content/toc-doc.json

Added some custom field docs to the TinaCMS docs. The previous docs where aimed at the older way of doing thing. This new page should better explain how things work now.
**Disclaimer: probably lots of typos**
Depends on https://github.com/tinacms/tinacms/pull/2059 and https://github.com/tinacms/tinacms/pull/2072 before being merged

Feat/custom fields TinaCMS docs

---

content/docs/schema-advanced.md
content/docs/schema.md
content/toc-doc.json

Adding an advance usage that @Enigmatical created. 
Love some eyes on it. 
Fixes #1029

Advance usage example

---

components/home/Features.tsx

updated the cli hero and added the `cd` command.

updated the cli hero

---

content/blog/who-is-logan-anderson.md

A blog post about Logan, ready to go out to the world. If someone could stamp so I can merge later today

Introducing logan post

---

content/docs/errors/ui-not-supported.md

Added a page to explain a warning message

added warning page

---

content/docs/errors/ui-not-supported.md

Fixed Error link

---

now.json

Adding a redirect from the packages back to our docs.

adding redirect for old package for cloudinary.

---

content/blog/mdx-powered-docs.md

Documentation starter blog post

---

content/docs/schema.md

Fix typo, add rich-text to field list

fix content modelling typo

---

now.json

Add some more redirects that I missed in https://github.com/tinacms/tinacms.org/pull/1088

Add more legacy redirects

---

content/docs/features/extending-tina.md
content/docs/schema.md

Pulling out some of the reference material out of the into Content Modelling doc.
This page could still use some work, but I think this makes things a bit more object based for an introductory doc

Simplify content-modelling concept doc

---

content/guides/tina-cloud/add-tinacms-to-existing-site/create-app.md
content/guides/tina-cloud/add-tinacms-to-existing-site/markdown-plugin.md
content/guides/tina-cloud/add-tinacms-to-existing-site/next-changes.md

- getPostsList is not a thing its getPostList
- Removing a # from a post
- Updating all queries and references

Adding changes so the guide works:

---

content/docs/schema.md
content/docs/tina-cloud/using-app.md

Just fixing a few things that seemed a bit awkward to me while doing dogfooding.

nitpicky grammar

---

data-api/fetchBlogs.ts

fixed the broken indices creation from this PR: https://github.com/tinacms/tinacms.org/pull/1110/files
https://github.com/tinacms/tinacms.org/actions/runs/1509055606

fix bad utils import

---

content/docs/cli-overview.md

Removed the guide field. Created references for each command.

Update cli reference

---

content/docs/setup-overview.md

Add note to cd into starter before running

cd into starter

---

content/docs/advanced/creating-field-component.md

Field-extension-improvements

---

content/pages/home.json
content/siteConfig.json

Updating SEO for more realistic representation of Tina,

Updating SEO for Tina

---

content/docs/tina-cloud/faq.md

Add info re: Vercel bug with Quickstart/dashboard select starter flow.

add in vercel bug to faq

---

content/toc-doc.json
now.json

- Remove guides redirects (we were redirecting from our active guide)
- Fix slugs of cloud docs, so that they appear selected when clicked

Nav & Redirect fixes

---

content/blog/using-the-power-of-mdx-with-tina.md

This will need to be merged on 12/09

Tina MDX blog post

---

content/docs/editing/active-field-indicator.md
content/toc-doc.json

Add experimental activate field indicator to our documentation.

Adding experimental activate field indicator 

---

package.json
yarn.lock

Upgrade node-saas so the site runs with node >=16

chore: Upgrade node-saas

---

content/docs-navigation.json
content/docs/reference/types/boolean.md
content/docs/reference/types/datetime.md
content/docs/reference/types/number.md
content/docs/reference/types/object.md
content/docs/reference/types/reference.md
content/docs/reference/types/rich-text.md
content/docs/reference/types/string.md

Adding the playground link into the nav
Also, adjusting existing links from old vercel deployment to the new one

Playground link

---

content/blog/2021-a-year-in-review.md

A year in review

---

content/guides/tina-cloud/add-tinacms-to-existing-site/create-app.md

A user reported a ticket where they were confused by this first page in the guide; The guide is "Adding TinaCMS to an existing NextJS app", but we tell them to create a Next app.

add note for existing nextjs sites

---

content/blog/new-year-new-cms.md

Blog Post: New year , New CMS?

---

content/docs/advanced/configuring-field-plugin.md
content/docs/editing/blocks.md
content/docs/editing/markdown.md

whoops! We had a few links to localhost from our docs

fix localhost links

---

content/docs/reference/toolkit/fields.md

date plugin is now part of default plugins
https://github.com/tinacms/tinacms/pull/1807

Date plugin docs fix

---

content/docs/index.md

remove call to action on intro page

---

content/blog/syntax-highlighting-with-tina.md

A new blog post that shows Tina devs how to use syntax highlighting with Prism

Tina syntax blog post

---

content/docs/tina-cloud/faq.md

PathToTina Documentation

---

content/docs/advanced/customizing-forms.md
content/docs/advanced/extending-tina.md
content/docs/features/data-fetching.md
content/docs/media-cloudinary.md
content/docs/schema.md
content/docs/tina-cloud/connecting-site.md
content/docs/tinacms-context.md
content/guides/tina-cloud/add-tinacms-to-existing-site/markdown-plugin.md

Documenting `useTina` instead of passing data into root TinaCMS container

useTina hook docs

---

content/docs/advanced/extending-field-plugin.md

Noticed a typo in the docs that would prevent users from being successful.

update field plugin docs

---

content/docs/editing/markdown.md

add section on rendering markdown to markdown field docs

---

content/guides/tina-cloud/add-tinacms-to-existing-site/next-changes.md

Update our guide to use useTina.
I think this could be made more clear, but I think we may want to revisit this whole guide in the near future anyways, as enough has changed since it was initially written.

Add useTIna in next guide

---

components/home/Actions.tsx
components/home/GlobalStyles.tsx
components/layout/CloudBanner.tsx
components/layout/Footer.tsx

While debugging ios rendering issues I came across a few issues, mostly spacing and on mobile.

Style Fixes

---

content/docs/editing/blocks.md
pages/api/graphiql.ts

Add docs on querying blocks

---

.tina/__generated__/_graphql.json
.tina/__generated__/_schema.json
.tina/__generated__/frags.gql
.tina/__generated__/schema.gql
.tina/__generated__/types.ts
.tina/schema.ts

Fixes issue with Hero block CTAs not displaying.

add homepage actions to schema

---

content/blog/simple-markdown-blog-nextjs.md
content/blog/using-tinacms-with-nextjs.md
utils/blog_helpers.test.ts
utils/blog_helpers.ts

This PR just updates two older posts so they use the latest Tina standards. This is our highest traffic post.
This PR also adds flex to the Relevant post function to include a check for last_edited front matter so we can automatically remove the warning if we update more posts.  I also added two more tests to test this.

2 Blog rewrites for SEO

---

content/docs/tina-cloud/data-layer.md
content/toc-doc.json

Documentation for the experimental data layer functionality in Tina Cloud

doc: initial data layer documentation

---

content/docs/advanced/edit-state.md

The link to `logout` is now `admin#/logout` and we're recommending a single file `pages/admin.js|tsx` rather than a whole directory.

2542 - Minor update for admin hash router change

---

content/blog/tina-is-in-beta.md
content/blog/using-the-power-of-mdx-with-tina.md
content/blog/using-tinacms-with-nextjs.md
content/docs/cli-overview.md
content/docs/graphql/cli.md
content/docs/introduction/tina-init.md

DO NOT MERGE UNTIL THE PR IS MERGED & PUBLISHED
Docs for https://github.com/tinacms/tinacms/pull/2639
PR to wait for here: https://github.com/tinacms/tinacms/pull/2640

docs: Use standard script names

---

components/layout/CloudBanner.tsx

Changed message on banner

---

components/layout/CloudBanner.tsx
components/layout/setup-overview.tsx

fix banner and quickstart link

---

content/docs/editing/blocks.md

closes #1234
TODO: add images (might be a separate PR that @spbyrne  can do next week.)

added visual blocks docs

---

content/docs/schema.md
content/docs/tinacms-context.md

docs: Add intro to contextual editing

---

.github/ISSUE_TEMPLATE/typical-issue.md

Update feature request issue template to match product roadmap

Update feature-request issue template

---

pages/_app.tsx

this turns on the branch switcher feature flag for tina cloud

enable branch switcher

---

content/docs/tina-cloud/dashboard.md
content/docs/tina-cloud/dashboard/users.md

Docs changes for new per project user management. Waiting on remaining work to be completed and migration to merge!

per-project user authorization docs changes (WAIT TO MERGE)

---

content/docs/editing/blocks.md

The example those not work if the type is not defined

Update example blocks.md

---

content/blog/data-layer-performant-editing.md

This is planned for next week 3/28 for 3/29

Data layer post

---

content/blog/read-only-tokens-content-anytime.md

A new post for read only tokens.

New post on Read only token usage

---

.tina/__generated__/_graphql.json
.tina/__generated__/_schema.json
.tina/__generated__/schema.gql
.tina/__generated__/types.ts
content/docs/graphql/queries.md
content/docs/graphql/queries/add-document.md
content/docs/graphql/queries/advanced/filter-documents.md
content/docs/graphql/queries/advanced/limitations.md
content/docs/graphql/queries/advanced/pagination.md
content/docs/graphql/queries/advanced/performance.md
content/docs/graphql/queries/advanced/sorting.md
content/docs/graphql/queries/get-document.md
content/docs/graphql/queries/query-documents.md
content/docs/graphql/queries/update-document.md
content/docs/tinacms-context.md
content/toc-doc.json
package.json
pages/api/graphiql.ts
pages/api/graphql.ts
yarn.lock

This adds documentation for the new data layer query functionality

feat: document querying with the data layer

---

content/docs/graphql/queries/advanced/filter-documents.md
content/docs/graphql/queries/advanced/limitations.md
content/docs/graphql/queries/advanced/pagination.md
content/docs/graphql/queries/advanced/performance.md
content/docs/graphql/queries/advanced/sorting.md
yarn.lock

Puts the actual link to the gh discussion in the associated documentation and updates the yarn.lock

update discussion links and deps for data layer

---

content/guides/tinacms/non-react-based-ssg/guide.md
content/guides/tinacms/non-react-based-ssg/meta.json
content/toc-doc.json

MVP Guide for adding Tina to a Hugo site

docs: MVP Hugo guide added

---

content/docs/features/data-fetching.md

Fixed spelling errors

---

content/docs/extending-tina/validation.md
content/docs/reference/types/boolean.md
content/docs/reference/types/datetime.md
content/docs/reference/types/image.md
content/docs/reference/types/number.md
content/docs/reference/types/object.md
content/docs/reference/types/reference.md
content/docs/reference/types/rich-text.md
content/docs/reference/types/string.md

Depends on https://github.com/tinacms/tina-playground/pull/10 to be merged first.
fixes #1284

update ui prop

---

content/guides/tinacms/non-react-based-ssg/guide.md

Use simple graphql in Hugo guide

update graphql version

---

components/DocumentationNavigation/VersionSelect.tsx

Add docs dropdown for pre:
- extending tina
- simplified graphql nodes

Add docs for pre-extending-tina

---

content/blocksPages/showcase.json

Fixed typos, pasted blurbs from each site, linked to code nation, etc

---

content/docs/graphql/read-only-tokens.md

added wild card docs

---

content/blocksPages/showcase.json

added new projects

---

content/blocksPages/showcase.json

added labrys.io to showcase

---

content/blocksPages/showcase.json

added protocol labs site to showcase

---

content/blog/basics-of-graphql.md

A GraphlQL basics post for Thursday

Adding graphql basics post

---

content/blocksPages/showcase.json

Added Paradise Helicopters to Showcase

---

content/docs/reference/types/object.md
content/docs/reference/types/rich-text.md

added blurb about rich text to defaultItem text

---

content/docs/reference/types/object.md
content/docs/reference/types/rich-text.md
content/docs/schema.md

Added new section on default values to content modelling doc and updated default values callouts on object and rich-text docs

---

content/docs/features/data-fetching.md
content/docs/tinacms-context.md

Docs suggestions

---

.tina/schema.tsx
content/blog/a-b-test-with-tina.md
utils/open-graph-image.tsx

Add NextJS middleware to title

Update ab test blog title

---

components/styles/DocsRichText.tsx

Prevent text from breaking layout

---

content/blog/tina-v-0.69.0.md
content/docs/cli-overview.md
content/docs/data-fetching/custom-queries.md
content/docs/data-fetching/overview.md
content/docs/editing/mdx.md
content/docs/features/data-fetching.md
content/docs/reference/content-api/data-layer.md
content/docs/tina-cloud/connecting-site.md
content/guides/tinacms/adding-internationalization-to-tina/guide.md
content/guides/tinacms/nextjs-data-fetching/guide.md
content/guides/tinacms/react-data-fetching/guide.md
package.json
pages/blog/[slug].tsx

Api driven logan client updates

---

content/blog/tina-v-0.69.0.md
content/docs/cli-overview.md
content/docs/graphql/cli.md

Couple of small docs update
cc @jamespohalloran

update to new command

---

content/docs/reference/media/overview.md
content/docs/reference/schema.md
content/docs/schema.md
content/docs/tina-cloud/connecting-site.md

update schema docs

---

content/blog/tina-v-0.68.14.md
now.json

Rename blog post to corect version.

update blog title

---

.tina/config.ts

Add missing client to defineConfig (fixes localmode in prod issue)

fix local-mode in prod bug

---

components/DocumentationNavigation/DocsNavigationList.tsx
content/toc-doc.json

Made a configurable status prop that can be used to set the nav-item badge

feat: configurable nav status badge

---

content/docs/tina-cloud/connecting-site.md

Add disclaimer on .env handling

docs: add note on .env

---

content/guides/tinacms/non-react-based-ssg/guide.md

Add note that permament non-react solution coming soon

docs: add disclaimer to non-react docs

---

.tina/__generated__/_schema.json
content/docs/reference/media/repo-based.md

Add a note about images not being able to be changed

---

README.md
content/blog/manage-your-media-with-cloudinary.md
content/docs/reference/media/cloudinary.md
content/docs/tina-cloud/connecting-site.md

Cleanup some bets practices around Tina's env handling (and update cloudinary's example to work out of the box )

docs: Update best practices for env

---

content/docs/tina-cloud/dashboard/projects.md

Correct spelling error in /docs/tina-cloud/dashboard/projects/

---

content/blog/tina-v-0.69.7.md

docs: post for 0.69.7 changelog

---

content/docs/reference/media/cloudinary.md

Clarify route needed for cloudinary integration

clarify route in cloudinary docs

---

content/docs/reference/media/repo-based.md

This is in response to an issue from discord: https://discord.com/channels/835168149439643678/1010902952522817569/1010953660194377801

add note about configuring next image domain for repo-based media

---

content/docs/reference/media/cloudinary.md
content/docs/reference/media/do-space.md
content/docs/reference/media/do-spaces.md
content/docs/reference/media/s3.md
content/toc-doc.json

Add documents for media store using DO Space and S3

---

content/blog/tina-version-0.69.13.md
content/docs/extending-tina/filename-customization.md
content/docs/reference/types/object.md
content/docs/reference/types/string.md

fixes ENG-598
fixes https://linear.app/tina/issue/ENG-598/list-true-not-fully-documented-in-reference-docs

added defaultItem docs

---

content/docs/reference/content-api/data-layer.md
content/docs/tina-cloud/dashboard/projects.md

Add accompanying documentation for the "Export Branch" feature

add documentation for export branch

---

content/siteConfig.json

Fix Twitter handle

---

content/guides/tinacms/nextjs-data-fetching/guide.md

Close [ENG-644](https://linear.app/tina/issue/ENG-644/document-ssr-with-nextjs)

Document for SSR with NextJS

---

components/blocks/Story.tsx

Quick test of the updated homepage demo site to see it in-context.

Update Homepage Demo Video

---

components/blocks/Story.tsx

Fix the flash between when the CSS loads and the video placeholder loads. Adds a background color to cover the text frame behind the video.

Video Flash

---

content/docs/reference/collections.md

Documents `allowedActions` in collections

added allowedActions docs

---

content/guides/tinacms/non-react-based-ssg/guide.md

Added framework selection prompt (https://github.com/tinacms/tinacms/commit/e339ad1dcf36a864de00d9b25fbd89137eff28f8)

Add framework select prompt

---

.tina/config.ts
package.json
pages/api/cloudinary/[...media].ts
yarn.lock

Setup cloudinary media in tinacms

cloudinary media

---

content/docs/forestry/accessing-cms.md

docs: Fix typos in accessing-cms.md

---

package.json
yarn.lock

security: bump tinacms

---

content/docs/tina-cloud/connecting-site.md

Fix GH Pages docs

---

content/docs/tina-cloud/connecting-site.md

Gh pages fixes

---

content/blog/self-hosted-datalayer.md

Before merging, need to fix each of the links

docs: self hosted blog post

---

content/blog/2023-02-security-update.md

Blog post on recent security alert

docs: security-alert

---

content/blocksPages/showcase.json

added shadowlion showcase

---

content/docs/reference/collections.md

I wanted to updated the docs for `match` but noticed the collection doc as a hole was a little lacking. So I added some updates.

update collections docs

---

content/docs/cli-overview.md

Pending merge [here](https://github.com/tinacms/tinacms/pull/3659)

Do not merge: Update cli docs to reflect latest changes

---

CONTRIBUTING.md

...and remove final period for consistency.

Docs: correct typo ('grammer' -> 'grammar')

---

content/docs/forestry/common-errors.md

Adds a blurb about the match property to the forestry migration docs.

add match docs

---

content/docs/errors/file-in-mutpliple-collections.md

Adds some error docs that we can link to in the CLI

add error match docs

---

content/docs/forestry/migrate.md

Minor typos. ('Setup' and 'backup' are nouns; 'set up' and 'back up' are the verb forms.)
NOTE: This document ends in the middle of a sentence ("Next we'll guide you through setting up some other Forestry-supported features like media, data files,") and doesn't seem to include the content referenced (how to set up media and data files).

Docs: corrected some typos on migrate.md

---

next.config.js

noindex on tina.io previews

---

content/docs/frameworks/gatsby.md

Gatsby work arounds

---

content/docs/reference/types/image.md

Docs on custom image format / parse

docs: custom image format docs

---

content/docs/forestry/overview.md

Fix a few typos, punctuation errors etc.

---

content/docs/reference/media/external/authentication.md

update netlify functions docs

---

content/docs/reference/media/repo-based.md

Added a small note about Syncing media to the repo based media docs.

update media docs

---

content/docs/forestry/migrate.md

spell check in 'migrate from forestry page'

---

content/docs/reference/media/external/cloudinary.md
content/docs/reference/media/external/do-spaces.md
content/docs/reference/media/external/s3.md

update media docs
I updated the List items to be heading because 
- they where unable to be edited in TinaCMS
- they were not rendering correctly (could not see the numbers)

TinaCMS content update by Logan Anderson

---

content/docs/extending-tina/custom-field-components.md

Add <code> tags around 'parse' to make this notice clearer.

Clarify a note in custom-field-components.md

---

content/docs/contextual-editing/react.md

Changed "body" to "title" in code example

---

content/docs/reference/content-api/data-layer.md
content/docs/tina-cloud/dashboard/projects.md

Docs for https://github.com/tinacms/tina-cloud/pull/1841

docs: Update after removing reset cache btn

---

components/layout/Footer.tsx

Add links to landing pages in footer

Footer links

---

content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

Some of these are stylistically a bit different, so wanted to open up a PR into yours incase we want to throw out these suggestions. 
A few main tweaks I've added:
- A little bit of an intro into why TinaCMS is a great fit for leveraging AI (in terms of its custom workflows)
- Mention some of the limitations of AI, as it can be a bit touchy of a subject.

ai-markdown blog tweaks

---

pages/_app.tsx

https://www.loom.com/share/908cd761af284f829c780fa93b1f4998?sid=809907d7-41db-4a53-b955-61efdb794707

Admin link for signed in users

---

.github/workflows/create-indices.yml
.github/workflows/nodejs.yml

Update node version in Github actions

update node version in github actions

---

components/blocks/Actions.tsx
components/blocks/FeatureGrid.tsx
components/blocks/Features.tsx
components/blocks/Hero.tsx
components/blocks/Testimonials.tsx
content/blocksPages/home.json

added click to edit to homepage blocks

---

content/toc-doc.json

Move Forestry migration guide into "Guides" section

Compress Forestry migration guide

---

components/layout/setup-overview.tsx

setu-overview grid cols

---

pages/docs/product-tour.tsx

Fix scroll on firefox on product-tour

fix product-tour on firefox

---

content/docs/reference/collections.md

changed datetime type on Example with default item

---

components/blocks/Actions.tsx

lower case and angle bracket

---

content/docs-navigation.json
content/navigation.json

Playground has some quirks, so remove links to it until we can invest some time fixing it up.

Remove links to playground

---

content/docs/reference/media/external/authentication.md

Fix auth docs to use config instead of schema

update auth docs to use config

---

components/layout/Footer.tsx

Capitalize the H in GitHub and align social icons in the footer

---

content/docs/reference/collections.md

Fix typo on Collections page.

---

content/docs/contextual-editing/router.md

fix: typo on router.md

---

content/docs/frameworks/nextjs.md
content/docs/introduction/using-starter.md

Adds two videos to the docs to help users get started.

add videos to docs

---

content/docs/self-hosted/migrating-from-tina-cloud.md
content/toc-doc.json

Adds a page that shows how to migrate from Tina Cloud to self-hosted

add migration video

---

content/guides/tinacms/internationalization/guide.md

The page had a couple of minor changes.

spell check and repetition

---

.github/ISSUE_TEMPLATE/new-bug.md
.github/ISSUE_TEMPLATE/new-feature.md

**Context:**
Templates improve readability of issues, and allow for the backlog to be concise and well traversable. Having uniform ways to publish issues (of different types) ensures that all relevant information is included for issues. 
**Screenshots:**
**Figure: New Feature Issue Template**
**Figure: New Bug Issue Template**

📖 Creating Templates for new feature and bug reporting

---

components/forms/EmailForm.tsx
components/layout/CloudBanner.tsx
components/layout/Footer.tsx

Context: 
As per the email from Adam with subject:  "🔥 URGENT: Tina homepage | Move location of newsletter subscribe controls", this code change will improve the visibility of the newsletter subscription by moving it from the Footer.tsx to CloudBanner.tsx. 
The UX changes checked by Betty.
Before:
After:

💄Moved newsletter subscription to the top for better visibility

---

components/layout/Footer.tsx
content/toc-doc.json

As per the [Code Auditor](codeauditor.com), a series of URLs were to be re-formatted. This PR addresses it.

⚒️ CodeAudit | Removing Slash and Periods from URLs 

---

content/blog/simple-markdown-blog-nextjs.md

XS issue - as per [SSW CodeAuditor](codeauditor.com) report-  made XS change to attribute name casing.

XS | ⚒️ Fix Attribute Name Casing

---

content/blog/Tina-sponsoring-the-serverless-DAYS-ANZ-conference.md

cc: @camillars 
blog post for tina sponsoring /serverless/DAYS

blog post - tina sponsors /serverless/DAYS

---

components/layout/Footer.tsx

netlify cms is now called decap cms

change netlifytoDecap

---

content/navigation.json

updated 'plugins & themes' to 'awesome tinacms'

---

next.config.js
now.json
pages/_app.tsx
pages/_document.tsx

connection to the new google tag manager (reviewed by SSW) to follow CTA buttons

Input Google Tag Manager for SSW

---

pages/_document.tsx

some text was left in header... meant to be a comment

remove header text mistake

---

content/blocksPages/home.json

CC: @JackDevAU 
As per my conversation with Jayden, emojis should not be used in UI, we should be using an icon if anything.

Remove emoji on CTA

---

content/blocksPages/home.json

Fixing issue https://github.com/tinacms/tina.io/issues/1818

Adding Google description

---

components/blocks/Showcase.tsx
content/blocksPages/home.json

Apart of #1827 was to link from logos in the carousel to their respective position on the showcase back. This was achieved by creating IDs per showcase section and link that from the carousel item

Added IDs : Logo Grid -> Showcase

---

components/layout/Navbar.tsx

cc: @bradystroud
As per email from @adamcogan
(Checked by Marcus, Eve)
Heya Josh 👋
https://youtu.be/Vagxix6k3ik?si=EdRsEkVCE1vU_vm2
Why at 14:29 does it flicker?
Can you fix?
This PR addresses this issue, re-working how the nav bar fixed mode is set. This was the issue causing the flickering behaviour

🐛 Nav Bar Flicker Bug 

---

components/layout/Navbar.tsx

fixes #1849 
Reverts tinacms/tina.io#1847

Revert "🐛 Nav Bar Flicker Bug "

---

components/blocks/Features.tsx
components/blocks/LogoGrid.tsx

As per #1840 there were a number of formatting issues with different sized views that @bettybondoc wanted changed.
This PR addresses this - ✅ _all test passed by betty_

💄Fix UI Issues

---

.github/ISSUE_TEMPLATE/ui-improvement.md

As per my conversation with Landon, we kept needing to create an issue...then there was no adequate template to use.

New issue template - UI/UX improvement

---

components/forms/EmailForm.tsx

As per #1829 when users clicked subscribe and the subscription status text was shown the layout of the modal was shifted. This PBI addresses this issue by reducing the vertical padding when the message is displayed.

🐛 Fixed Subscribe Modal Layout Shift 

---

content/docs/contributing/setting-up.md

On a call with @JackDevAU @bradystroud and @adamcogan 
We noticed that the contributing guidelines were really out of date - added a TODO and link to the latest docs on the TinaCMS repo

Setting-up doc - add TODO to latest docs

---

components/DocumentationNavigation/DocsHeaderNav.tsx
components/DocumentationNavigation/DocsNavigationList.tsx
components/blocks/RecentPosts.tsx
components/layout/Footer.tsx
components/layout/Navbar.tsx
components/logo/TinaIcon.tsx
components/ui/Button.tsx
components/ui/DynamicLink.tsx
pages/blog/page/[page_index].tsx
pages/community.tsx

As per #1826 we have updated the <Link> components to get rid of child anchor tags and remove `legacyBehaviour` tags

💸 Remove 'legacyBehaviour' tag from <Link> 

---

components/blocks/Features.tsx
components/blocks/Flying.tsx
components/blocks/Hero.tsx
components/blocks/LogoGrid.tsx
components/blocks/Quote.tsx
components/blocks/Showcase.tsx
components/layout/MarkdownContent.tsx
pages/404.tsx
pages/community.tsx

As per https://github.com/tinacms/tina.io/issues/1832 this PR addresses updating the <img> to use React <Image>'s instead. Tested.

💸 <img> to <Image> 

---

.github/dependabot.yml
tina/schema.tsx

As per https://github.com/tinacms/tina.io/issues/1842 we have created a dependabot.yml file so that we can manage our dependency updates better.

🤖 Dependabot.yml Add

---

components/blocks/CodeButton.tsx
pages/_document.tsx

cc: @landonmaxwell 
Now that Scott has successfully exported all of the items in his GTM container, and we have imported the relevant tags into the SSW GTM. So we have removed references to the old GTM container. 
related to #1922

Removed references to the old GTM

---

content/docs/tina-cloud/faq.md

Update faq.md - Small fixes to content

---

content/blocksPages/media.json

Levi had brought up that there was no content on the media page.
Using GitLens i restored the content

♻︎ Restoring Content on Media Page

---

content/docs/tina-cloud/faq.mdx

for email `FAQs - Include the tech stack`

📝 FAQ - add tech stack

---

next.config.js

fixes broken link found in https://github.com/tinacms/tinacms/issues/4427

next.config.js - modified Tina Cloud doc redirect

---

content/docs/reference/media/external/authentication.mdx

Opening a new PR due to issues with the previous one. See original PR: https://github.com/tinacms/tina.io/pull/1872 
> See [original PR on tinacms](https://github.com/tinacms/tinacms/pull/4598) and [discord discussion](https://discord.com/channels/835168149439643678/1256612728257384511) for reasoning why `tina-lock.json` should be mentioned within this section to prevent developers from running against a wall.

Add tina-lock.json info

---

content/docs/editing/blocks.mdx
content/docs/editing/markdown.mdx
content/docs/tina-cloud.mdx
content/docs/tina-cloud/api-versioning.mdx
content/docs/tina-cloud/dashboard/organizations.mdx
content/docs/tina-cloud/deployment-options/github-pages.mdx
content/docs/tina-cloud/deployment-options/netlify.mdx

Small content improvements to Tina Docs

---

components/blocks/CompareBox.tsx
content/blog/Introducing-the-Deep-Dive-Video-Series.mdx

cc: @bettybondoc 
Hi Josh,
As per our conversation, I've noticed that the text in the competitors' table isn't aligning well on smaller screens.
1. Fix the alignment for the mobile and tablet view
2. Remove the company name in the mobile view, leaving just the logomark This change should provide more space for the text on mobile devices
----
**Figure: New Competitors Mobile View**

💄Mobile UI Compare Box fixes

---

components/blocks/Pricing.tsx

cc: @wicksipedia @bettybondoc
For the new pricing component there were issues from the lg-1250px view. So we extended the medium view up until 1250px and then from 1250px onwards uses the large view

Fix pricing sizing

---

components/blocks/Pricing.tsx

Small design addition from the team. Adding hover background to the tier users are hovering over 
**Figure: Hover on business**

💄Hover Background for Pricing 

---

components/blocks/LogoGrid.tsx

test passed by @bettybondoc, only dropped a bunch of the padding to make the mobile view more in sync

💄Reduced height of padding in Trusted by component 

---

content/blog/Improving-TinaCloud-Indexing-with-Native-Git-CLI-and-Sparse-Checkout.mdx
content/blog/TinaCMS-Version-21.mdx

<details><summary>Details</summary>
<p>
</p>
</details>

Perf blog - adding perf prefix

---

content/blocksPages/about.json

⌛ About Page – Timeline / History of Tina

---

content/navigation.json

The about page has been added to the navbar under resources, support and another menu item were moved to the community tab.
<details>
</details>

Updating navbar as per instructions

---

components/blocks/IconBanner.tsx
components/blocks/Quote.tsx
content/blocksPages/home.json
tailwind.config.js

Orange gradient has been changed to a seafoam gradient as per the hex codes in the [given mockup](https://www.figma.com/proto/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=1192-3197&t=8UonKKaYdSdBmy9o-1&scaling=scale-down-width&content-scaling=fixed&page-id=997%3A2060&starting-point-node-id=1192%3A3197)
<details>
</details>

🎨 Homepage and quote banner colour updated (orange to seafoam)

---

components/blocks/Pricing.tsx
content/blocksPages/pricing.json

Prospective change to the pricing page.
<details>
</details>

💰 Pricing updates via Tina

---

.github/workflows/dispatch-create-whats-new-page.yml

Corrected name of script being called -  most recent run failed as the script being called didn’t exist.

dispatch-create-whats-new-page - fix script location

---

README.md

README - Add vision

---

.github/workflows/create-indices.yml
.github/workflows/nodejs.yml

Dependabot replacement PR
🤖🤖🤖
This pull request updates the GitHub Actions workflows to use the latest version of the `pnpm/action-setup` action. The most important changes include updating the version from v2 to v4 in two workflow files.
Updates to GitHub Actions workflows:
* [`.github/workflows/create-indices.yml`](diffhunk://#diff-cc7004aa323a9bdc47493a22b704cb7b30d7fe73eca036d5bd00928f173b5244L17-R17): Updated `pnpm/action-setup` from version 2 to version 4.
* [`.github/workflows/nodejs.yml`](diffhunk://#diff-e98936aa52a6dd7416e4296e9628456227d834f7245967383fd9ff80fd985dadL19-R19): Updated `pnpm/action-setup` from version 2 to version 4.
🤖🤖🤖
<details>
</details>

➕ Updating the `pnpm/action-setup` action

---

components/ui/GraphQLQueryResponseTabs.tsx

📝 Updating comments – specifying that certain TODO's are also tech debt

---

.github/ISSUE_TEMPLATE/docs-update.md

This pull request introduces a new issue template specifically for proposing changes to the official documentation. The template aims to streamline the process of suggesting and discussing documentation updates.
New issue template for documentation changes:
* [`.github/ISSUE_TEMPLATE/docs-update.md`](diffhunk://#diff-fdefe3185417a4481fbe9544923e8a87beb2dc8faff413eb0fde3ec9f01aa251R1-R28): Added a new template to propose content changes to the official Tina.io documentation. This template includes sections for describing the current issue, outlining the proposed changes, listing tasks, providing additional context, and adding relevant screenshots.
I very often create PBIs for this kind of stuff and it would save me time 🙏

📝 Adding a new GitHub issue template for docs changes

---

content/docs/reference/media/external/do-spaces.mdx

cc: @Jord-Gui 
As per #2076 someone from the community raised that there was an error with the DOS docs. As per my conversation with @Jord-Gui, who is currently investigating DOS, this PR addresses fixing this doc page.

📑 Docs | Update Digital Ocean Spaces doc

---

content/blocksPages/enterprise.json

Fixed all the media on the /enterprise page and made sure its consistent with the hompage 
**Figure: Logo grid fixed✅**

fix media on Enterprise page

---

.github/ISSUE_TEMPLATE/docs-update.md
content/blocksPages/home.json

Urgent events fix

---

content/docs/reference/media/external/s3.mdx

add doc on CORS configuration for S3 media manager

---

content/docs/guides/converting-gatsby-to-tina

- Fixed: https://github.com/tinacms/tina.io/issues/2368

📝 Added a guide about converting a Gatsby blog to TinaCMS

---

pages/whats-new/tinacloud.tsx
pages/whats-new/tinacms.tsx

Adding SEO Title and description info as per https://github.com/tinacms/business-backlog/issues/23

SEO Info for whats new pages

---

.github/ISSUE_TEMPLATE/docs-update.md
components/blocks/Quote.tsx

Adding new Quote blocks was erroring things out.
to ===>
I've given it a default value so it's no longer trying to read null.
<details>
</details>

Fix to the Quote Block

---

.github/ISSUE_TEMPLATE/docs-update.md
components/blocks/Quote.tsx
pages/_app.tsx

Landon asked me to add Hotjar embed into the website.
As we're using react/Next.js, I've added it into a useEffect() hook on the _app.tsx file (should wrap every page).
Please test this. Thanks!
<details>
</details>

📈 Hotjar install

---

content/docs/guides/converting-gatsby-to-tina.mdx

📝Documentation - Polish Gatsby MDX Migration Guide.

---

components/blocks/RoadmapGrid.template.ts

**Figure: ❌ Bad - Not helpful labels**
**Figure: ✅ Fixed - helpful labels**
<details><summary>Details</summary>
<p>
</p>
</details>

💄 UX - Roadmap - add item headings

---

components/blocks/CarouselFeature.tsx

Revert "🐛 UI fixes to Key Features Component "

---

content/blocksPages/home.json

Reverts tinacms/tina.io#2435
Fixed the demo

Adding the demo button back – it's been a long day

---

components/ui/Overlay.tsx

dropepd z-index on overlay (forgot to test tablet view earlier)

drop overlay z-index

---

components/DocumentationNavigation/DocumentationNavigation.tsx
components/DocumentationNavigation/VersionSelect.tsx

As per #2333 there were some inconsistent overlaps of content in the docs header. 
Test passed by @bettybondoc fixed it with her
**Figure: New Header**
**Figure: Old Header**

💄 Docs Mobile - Header Changes

---

components/blocks/CompareBox/CompareBox.tsx

Some more null checks were needed so you can create a new comparison block. This fixes that.
Specifically images were trying to render with a null source, and the mapping is no longer needed to set defaults (criteria mapping is done on save).
This is a quick fix and there's more room for improvement (e.g. you need to put at least 4 or 5 companies and a couple criteria in before it looks "normal").

Comparison Box – Creating a new block

---

components/blocks/Pricing/Pricing.tsx
package.json
pnpm-lock.yaml
tailwind.config.js

As per https://github.com/tinacms/tina.io/issues/2378
**Changes**
**Figure: All buttons now aligned**

Annual pricing improvements

---

content/docs/self-hosted/overview.mdx

Fix broken link reported here https://github.com/tinacms/tinacms/issues/5277

fix: broken link to self-hosted limitations

---

content/whats-new-tinacloud/2024.11.43.mdx

- Removed comment to fix rendering issues.
- Removed PR link as TinaCloud is a private repo.
Figure: Broken rendering

fix: Removed comment to fix rendering issues

---

content/blocksPages/home.json

Updating a non-existent file to solve safari issues

---

content/docs/reference/types/rich-text.mdx

I set the order in the documentation to match the current default ordering.
---

Add list of toolbarOverride options to documentation

---

pages/_app.tsx
pages/_document.tsx

cc: @landonmaxwell 
As per #2613 wwe have installed microsoft clarity

🌠 Add Microsoft Clarity

---

components/blocks/Blocks.tsx
components/blocks/Events/Events.tsx
components/blocks/FeatureCarousel/CarouselFeature.tsx

Safari wasn't eating webm's on mobile (crashing out as per #2592).
If a mobile environment is detected the video components aren't displayed.
The feature carousel is now being client rendered to achieve this.
In addition, reduced some tech debt (blue headings were all h1, changed them to h2s are they're not being used as main page headings).

Solving Safari Issues – Mobile Version of the Feature Carousel

---

content/docs/forestry/migrate.mdx

Fixed typo in URL. Checked existing PRs but could not find one that tackles this typo. Ignored other contribution requirements as this is a very small change. Hope that's okay.

Fix typo in URL

---

components/blocks/Blocks.tsx
components/blocks/FeatureCarousel/CarouselFeature.tsx
components/blocks/Features/Features.tsx
components/blocks/Testimonial/Testimonials.tsx
public/svg/play-button.svg
tailwind.config.js

(1) The testimonials will be contracted in mobile views, concealed by a see more button.
The first three testimonials will be shown in this contracted view, with the third one fading out slightly via an image mask.
(2) Showing the third feature in mobile while in the hidden view, with the same image mask as for testimonials.
Slightly educed the opacity of the YT play button centre and added 5% of the hover opacity to video boxes by default so there's some kind of placeholder as they load in.
(1) The functionality of this kind of 'show all' list should be extracted into it's own class and passed to the mappings as a wrapper.
(2) The mobile detection functionality should be centralised.
(3) Image mask wasn't being applied when I included it in the tailwind config, so I'm using raw css for …

💄 Mobile Experience Homepage Upgrade

---

pages/docs/product-tour.tsx

cc: @adamcogan 
📧 Introduction to TinaCMS | TinaCMS Docs #1
Hi Josh
https://tina.io/docs/product-tour
I really enjoyed looking through this new UX 🙌
> Here we give a quick 2 minute overview of TinaCMS, and how it fits into your website.
1. I find it odd that the first two lines here are in blue writing, different from the rest.
...
-----
This PR addresses task #1 by overriding the DocsAndBlog styling component

🐛 Product Tour Text Color Align 

---

app/layout.tsx

As per [🐛 Events Page - Favicon](https://github.com/tinacms/tina.io/issues/2696)
I have just explicitly defined the favicon in the app router `layout.tsx`

🔌 explicitly define favicon in app router

---

next.config.js

Adds security headers to next config to prevent loading the site in an iframe
**Before:**
**After:**

next.config.js - Add security headers

---

next.config.js

This should allow the site to be editable in the Tina editor (since it needs to load the site in an iframe on the same origin)

next.config.js - Update security headers for frame options and content security policy

---

package.json
pnpm-lock.yaml

CI/CD Recommends Installing Sharp For Prod Image Optimisation – used by Next.js automatically if installed

---

components/layout/Footer.tsx
components/logo/TinaIcon.tsx
content/footer/Master-Footer.json

cc @wicksipedia 
As per @adamcogan 's email: **Re: TinaCMS – orange footer 🍊**
- Links in lowercase
- bigger llama logo
- fixed "What's"
- removed extra headings "PRODUCT" and "RESOURCES"
From
To

Update Footer.tsx styling

---

components/tinaMarkdownComponents/docAndBlogComponents.tsx

Fixed the doc and blog scroll behaviour by using an offset and the `window.scrollTo()` function to custom set our offset from the "top of the page"
https://github.com/user-attachments/assets/0a2c14ae-5fc4-4afd-8770-0235fbe150d7
**Figure: New Scroll Behaviour**

🐛Fix Header click behaviour

---

components/DocumentationNavigation/Breadcrumbs.tsx
components/DocumentationNavigation/DocsNavigationList.tsx
components/DocumentationNavigation/DocumentationNavigation.tsx

Updating routing code to app router compatible :)

---

content/whats-new-tinacloud/2025.02.83.mdx

This PR adds the release notes for TinaCloud 2025.02.83.
This was created automatically by a GitHub Action - `.github/workflows/dispatch-create-whats-new-page.yml`

Release Notes - Add TinaCloud 2025.02.83-2

---

content/whats-new-tinacloud/2025.02.82.mdx

This PR adds the release notes for TinaCloud 2025.02.82.
This was created automatically by a GitHub Action - `.github/workflows/dispatch-create-whats-new-page.yml`

Release Notes - Add TinaCloud 2025.02.82-2

---

app/search/page.tsx
components/AppRouterMigrationComponents/Docs/docsSearch/SearchComponent.tsx
utils/new-search.tsx

See [Fix search functionality and double quotes issue in TinaCMS Doc Search](https://github.com/tinacms/tina.io/issues/2729)
Fixed issues with exact search using double quotes and fixed problems with duplicate display of quotation marks
Here is a comparison of before and after the changes:
**Figure 1: Before - when using double quotes for exact search, the returned results do not actually match the criteria (containing "tina")**
**Figure 2: Exact search only returns perfectly matching content, quotes are not displayed repeatedly, and there is a small badge indicating that you are currently using exact search**
**Since the original PBI did not provide detailed requirements regarding the search functionality, please feel free to thoroughly test whether there are any aspects that do not meet …

🐛 Fix search functionality and double quotes issue in TinaCMS Doc Search

---

components/tinaMarkdownComponents/docAndBlogComponents.tsx

add vertical spacing and round the edge of images

---

components/blocks/Showcase/Showcase.tsx
content/blocksPages/roadmap.json
content/blocksPages/showcase.json

See https://tina.io/roadmap and https://tina.io/showcase – this resolves the bottom spacing issues

Adding bottom spacing where appropriate

---

components/AppRouterMigrationComponents/AppFooter.tsx

Since this one didn't work: https://github.com/tinacms/tina.io/pull/2828

To fix footer social icons on mobile

---

content/docs-toc/docs-toc.json
content/docs/tina-cloud/deployment-options/alibaba-cloud.mdx
content/docs/tina-cloud/deployment-options/github-pages.mdx

Add docs for deployment on Alibab Cloud

---

content/docs/tina-cloud/deployment-options/alibaba-cloud.mdx

Update the TinaDocs for deployment on Alilibab Cloud Server

---

content/docs/introduction/faq.mdx

cc @sethdaily 
as per @adamcogan 's request

Adding numbers to faq.mdx + removed useless Q&A

---

components/tinaMarkdownComponents/docAndBlogComponents.tsx

as per @adamcogan request
- margin bottom to paragraphs
- more margin top to headings
- ol consistent with ul (less margins in them)
- borders in images
- white bg in blockquotes
- etc.

Improving readability docAndBlogComponents.tsx

---

content/blocksPages/zh/about.json

About Page - Add Chinese Version Json File

---

app/not-found-client.tsx

Fix the image overlap issue on not-found page

---

content/blocksPages/zh/roadmap.json

Roadmap - Chinese translation

---

content/blocksPages/zh/enterprise.json

Enterprise - Add Chinese translation

---

content/blocksPages/zh/compare-tina.json
content/blocksPages/zh/home.json

Add Chinese version for compare-tina page

---

content/blocksPages/zh/showcase.json

Update the headline for "showcase" page

---

components/AppRouterMigrationComponents/AppNavBar.tsx
components/AppRouterMigrationComponents/LanguageSupportAlert.tsx
content/navigationBar/navMenuZh.json

Alert Component Improvement

---

app/conference/page.tsx

Small Fixes with Adam

---

components/AppRouterMigrationComponents/AppNavBar.tsx
middleware.ts
utils/locale.ts

Fix the Language Switching Issue on Home Page

---

content/docs/editing/blocks.mdx

As per #2983 fixing closing strings

🐛 XXS | fix closing string

---

content/docs/beginner-tutorials/hello-world.mdx

test markdown

---

content/docs/beginner-tutorials/hello-world.mdx

update hello world

---

content/blocksPages/zh/home.json

Update the Chinese Homepage

---

content/docs/setup-overview.mdx

Translate quick start

---

content/docs/using-tina-editor.mdx

trigger translate

---

content/docs/using-tina-editor.mdx

Doc translate editing experience

---

content/docs-toc/learn-toc.json
content/docs/guides/naming-conventions.mdx

I noticed the title for this doc wasn't capitalized like the other docs so I made it consistent

TinaCMS content update

---

content/docs/tina-cloud/deployment-options/alibaba-cloud.mdx

Update the Docs Page for Deployment on Alibaba Cloud

---

.github/scripts/create-pr.js

Add labels to Auto-Translation Github Action

---

components/ui/DocsPagination.tsx

Quick fix to the Chinese Leakage

---

utils/docs/getDocIds.ts

Fix the Highlight Error on Chinese Docs Page

---

content/docs/drafts/editorial-workflow.mdx

I noticed this was old - but we just updated it

Update 'last edited' date

---

components/ui/DocsPagination.tsx
components/ui/DynamicLink.tsx
content/docs-zh/index.mdx
utils/locale.ts

Update the Pagination Controls

---

components/AppRouterMigrationComponents/AppFooter.tsx

make changes to css per Adam's request

---

components/AppRouterMigrationComponents/AppFooter.tsx

Footer style changes

---

components/AppRouterMigrationComponents/AppNavBar.tsx
components/ui/DocsPagination.tsx

Mobile toggle menu fix

---

components/AppRouterMigrationComponents/AppNavBar.tsx
components/ui/DocsPagination.tsx

Mobile flyout banner

---

components/AppRouterMigrationComponents/Docs/DocumentationNavigation/DocsNavigationList.tsx

Update Sidebar Navigation Behavior

---

components/blocks/FeatureCarousel/CarouselFeature.tsx

fix safari screen movement

---

app/conference/ConferenceClient.tsx
content/conference/TinaCon2025.mdx

Removed workshops from agenda
Moved workshop sessions to talks

Fix tinacon 

---

app/[...slug]/page.tsx

rm tinacon banner

---

content/docs/beginner-tutorials/routing.mdx

missing } in code sample

---

app/docs/[...slug]/docs-client.tsx
app/zh/docs/[...slug]/docs-client.tsx
components/AppRouterMigrationComponents/Docs/DocumentationNavigation/DocsNavigationList.tsx
components/AppRouterMigrationComponents/Docs/docsMain/tocOverflowButton.tsx
components/AppRouterMigrationComponents/Docs/toc/index.tsx
content/docs-toc/learn-toc.json
content/docs-toc/learn-zh-toc.json
utils/docs/getDocProps.ts
utils/enhancedPathMatching.ts

Update zh-docs toc behavior

---

components/AppRouterMigrationComponents/AppNavBar.tsx

As per https://github.com/tinacms/tina.io/issues/3162 
**Figure: New Nav Bar**

right to down chev

---

app/layout.tsx
components/AppRouterMigrationComponents/CloudBanner.tsx
content/navigationBar/navMenu.json

cc: @isaaclombardssw @wicksipedia @adamcogan as per our conversation, adding the star banner back with a more modern feel

add-back-star-banner

---

app/docs/[...slug]/page.tsx
content/blog/announcing-extending-tina.mdx
content/blog/evolution-of-inline-editing.mdx
content/blog/introducing-media-manager.mdx
content/blog/tina-cloud-and-nextjs-the-perfect-match.mdx
content/blog/using-graphql-with-the-filesystem.mdx
content/docs/extending-tina/overview.mdx
content/docs/setup-overview.mdx
content/docs/tina-cloud/schema-migration.mdx

Fixing broken links found in SEMRush - see https://github.com/orgs/tinacms/projects/44/views/1?pane=issue&itemId=110573792&issue=tinacms%7Ctina.io%7C3428

Semrush Broken Links

---

content/blocksPages/roadmap.json

Update roadmap.json to add missing full stop

---

components/AppRouterMigrationComponents/Docs/toc/index.tsx

As per https://github.com/tinacms/tina.io/issues/2992
Fixed scrolll behaviour of right side ToC 
https://github.com/user-attachments/assets/5f509123-4d2e-460e-afc6-90257a306830
**Video: Before**
https://github.com/user-attachments/assets/951759b5-eab4-4856-bbc6-e0227db5fed2
**Video: After**

Fix scroll offset

---

app/conference/ConferenceClient.tsx
app/conference/page.tsx
content/blocksPages/home.json
content/docs/beginner-tutorials/new-tinacms-site.mdx
content/docs/beginner-tutorials/the-content-model.mdx
content/docs/contextual-editing/overview.mdx
content/docs/contextual-editing/react.mdx
content/docs/graphql/queries.mdx
content/docs/tina-cloud/migration-overview.mdx

As per https://github.com/tinacms/tina.io/issues/3568

SEMRush - Meta Tag and Description Fixes

---

.github/workflows/dispatch-create-whats-new-page.yml

Pipeline - Adding step to get app token

---

.github/workflows/dispatch-create-whats-new-page.yml

Removing Auto Merge

---

app/[...slug]/client-page.tsx
app/[...slug]/page.tsx
components/blocks/RecentPosts/RecentPosts.tsx
content/blocksPages/zh/home.json
tina/queries/post.gql

Update the post query function on Chinese home page

---

.github/package.json
.github/scripts/fix-translation-paths.js
.github/workflows/auto-translate-docs.yml
components/AppRouterMigrationComponents/footer/constants.ts

Update the Auto-Translation Action

---

.github/package.json
.github/scripts/fix-translation-paths.js
.github/scripts/translate-mdx.js
.github/workflows/auto-translate-docs.yml

Optimize the auto-translation Action

---

content/blog/announcement-tina-cloud-is-officially-in-alpha.mdx

fix redirect loop

---

content/docs/reference/types/rendering-markdown.mdx

Relates to https://github.com/tinacms/tinacms/issues/5890#issuecomment-3112353087 and https://github.com/SSWConsulting/SSW.Rules/issues/1822

Add example for customizing code_block in Tina Markdown

---

.github/workflows/codeauditor-scan.yml

As per https://github.com/SSWConsulting/SSW.CodeAuditor/issues/947 this creates a weekly CodeAuditor scan that runs every Thursday.

Set up weekly CodeAuditor scan

---

components/AppRouterMigrationComponents/AdminLink.tsx
components/AppRouterMigrationComponents/AppNavBar.tsx

As per #3797, Tested on preview https://tina-js1e1kg4x-tinacms.vercel.app/docs/using-tina-editor

Fix Admin Link routing w/ current path 

---

content/blocksPages/showcase.json

temporary remove kunai logo. in the future will be replaced with the company logo that acquired kunai

refactor: showcase.json

---

content/events/master-events.json

Fix broken image

---

content/docs/reference/types/rich-text.mdx

Relates to https://github.com/tinacms/tinacms/issues/5008#issuecomment-2549641293

docs: update docs to showcase toolbar overrides and floating toolbar visibility option

---

app/docs/[...slug]/page.tsx
app/docs/r/[alias]/page.tsx
components/tinaMarkdownComponents/docAndBlogComponents.tsx

Fixes a Hydration Error in the docs 
Also fixes the generateStaticParams for the Alias routes by using the locla filesystem instead of the Tina client

Fix Alias and Hydration Err

---

content/footer/Master-Footer.json

As per email subject "Re: Tina Feedback - Finding Documentation"
**Figure: Updated text Documentation**

Updating text Introduction to Documentation

---

content/navigationBar/navMenu.json

cc @adamcogan @joshbermanssw @wicksipedia 
Closes https://github.com/tinacms/tina.io/issues/3963

Update main menu structure for Tina.io
