content/docs/gatsby/manual-setup.md
This adds one more config item to the existing code sample on the [Gatsby manual setup](https://tinacms.org/docs/gatsby/manual-setup) page, which appears to be required.
When following the current documentation, adding the `gatsby-plugin-tinacms` plugin to your `gatsby-config.js` results in this error: 
`Unhandled Rejection (TypeError): Cannot read property 'position' of undefined`
Adding plugin options for sidebar position will fix this and meet the description of this first step of manual setup.
I've commented the `hidden` key out since it's not required for things to work, but might make sense to keep since it hints at how you'd probably want this configured for a real project.
Hope this helps!
=> Documentation: Update example code on Gatsby manual setup page.

content/blog/2020-03-09-release-notes.md
This will make it show up after the visual editing post
=> docs: correct publication time for release notes

content/docs/gatsby/quickstart.md
Was browsing the site and noticed what looks like broken markdown parsing for this heading.
https://tinacms.org/docs/gatsby/quickstart
=> Add a space for 'Use a starter' heading

components/ui/DocsNav.tsx
- adds an "Overview" link as first child if nav item has both a slug and children, so parent item can be used exclusively to toggle nav
- fixes highlight logic so highlights remain correct
- fixes expand logic so parent menus can be collapsed even if currently viewing a child page
=> Improve docs dropdown behavior

README.md, components/layout/MarkdownContent.tsx, content/docs/cms/alerts.md
- change syntax from default `[[ Shortcode ]]` to Jekyll-style `{{ Shortcode }}` so they aren't escaped by the WYSIWYG
- update readme to explain shortcodes
=> Shortcode updates

components/layout/OpenAuthoringSiteForm.tsx, open-authoring/OpenAuthoringModalContainer.tsx, open-authoring/error-interpreter/index.ts, open-authoring/withErrorModal.tsx, pages/blog/[slug].tsx, pages/blog/page/[page_index].tsx, pages/community.tsx, pages/docs/[...slug].tsx, pages/docs/index.tsx, pages/index.tsx, pages/teams.tsx
Move some of the error interpretting logic from the SiteForm to a ErrorModal HOC.
Now we don't have to pass errors from the initial content-load through several DOM elements (which caused issues when we didn't have a fallback state).
Also, OpenAuthoringModalContainer now only takes in an ErrorUI component
=> Error cleanup

package.json, pages/blog/page/[page_index].tsx, pages/rss.xml.tsx, utils/blog_helpers.ts, utils/github/getMarkdownData.ts, yarn.lock
This replaces remove-markdown with a different approach to stripping markdown. This is motivated by a ReDos vulnerability in remove-markdown: https://github.com/stiang/remove-markdown/issues/47
Something about remove-markdown's regex was causing very slow execution for specific markdown payloads. This slows down builds, dev mode, and preview mode (any time that `getStaticProps` is run.)
Replacing remove-markdown improves dev mode TTFB for /docs/forms from **12.5s** to **1.1s**.
This PR also includes some formatting tweaks to excerpts:
- always truncate on word boundary
- only add an ellipsis if there is more content not shown in the excerpt (likely, but not guaranteed)
=> Improve excerpt generation

content/docs/getting-started/introduction.md
Next.js support is currently better than Gatsby's so I reordered the content copy
=> Reorder copy: put Next.js stuff before Gatsby stuff

pages/blog/[slug].tsx
We want to return a 404 for routes that don't exist, and setting `fallback: false` does that. However, Now does not currently support preview mode for dynamic routes that aren't created by `getStaticPaths` when fallback is false.
This _should_ fix the issue where creating a new blog post in edit mode results in a 404 error.
=> set fallback to true, but 404 on fallback route

pages/blog/[slug].tsx, pages/blog/page/[page_index].tsx, pages/community.tsx, pages/docs/[...slug].tsx, pages/docs/index.tsx, pages/index.tsx, pages/teams.tsx
This error surface with the upgrade to Next 9.3.0. Causes the Error modals to not be rendered in preview-mode
=> fix(errors): fix issue where errors not parsed as JSON

components/cms/Toolbar.tsx, open-authoring/PRPlugin.tsx, open-authoring/useOpenAuthoringToolbarPlugins.tsx
This PR implements the changes described in [RFC 0005](https://github.com/tinacms/rfcs/blob/master/0005-toolbar-widget.md)
* The `toolbar:form-action` and `toolbar:status` plugins have been removed. Those components are always rendered now. This is the same way it works in the Sidebar.
* The `toolbar:git` plugin has been replaced with a more generic `toolbar:widget`. 
* These widgets are ordered by `weight`.
* Any `props` defined on the widget are passed to the component.
=> Toolbar Refactor

open-authoring/open-authoring/OpenAuthoringAuthModal.tsx, open-authoring/open-authoring/OpenAuthoringProvider.tsx, package.json, yarn.lock
When you click 'Create Fork' or `Continue to GitHub` (async actions) loading dots are displayed in place of button text & the button is disabled.
=> chore: display loading state on async actions

open-authoring/open-authoring/AsyncButton.tsx, open-authoring/open-authoring/OpenAuthoringAuthModal.tsx, open-authoring/toolbar-plugins/pull-request/PRModal.tsx
This uses the AsyncButton for the 'Create PR' button so it gets a loading state / disabled after it's pressed.
Fixes #300
=> refactor: extract AsyncButton, use for PR button

open-authoring/OpenAuthoringError.ts, open-authoring/github-error/OpenAuthoringErrorModal.tsx, open-authoring/github-error/github-interpeter.ts, pages/blog/[slug].tsx, pages/community.tsx, pages/docs/[...slug].tsx, pages/docs/index.tsx, pages/index.tsx, pages/teams.tsx, utils/github/GithubError.ts, utils/github/getContent.ts, utils/github/getDecodedData.ts, utils/github/getFiles.ts, utils/github/useGithubFileForm.ts, utils/plugins/MarkdownCreatorPlugin.ts, utils/plugins/github-api/GithubApi.ts, utils/plugins/github-api/GithubError.ts
- Replace "OpenAuthoring" error with "GithubError".
- in [getContent](https://github.com/tinacms/tinacms.org/compare/github-content-error-refactor?expand=1#diff-ae9280b5816ca3c82ebdd87dddcb4c6b), we were returning error with response instead of bubbling the error up. 
- In [a few cases](https://github.com/tinacms/tinacms.org/compare/github-content-error-refactor?expand=1#diff-c379cba35ed0c09a44ea341b3ef071c4L40), we were catching error, and creating a new error with same format
=> GitHub content error refactor

README.md
TINA_WATCH is used for local dev, and not TINA_USE
=> TINA_WATCH readme fix

pages/index.tsx
This adds a simple block setting to the homepage selling points to demo the block settings menu.
=> add block setting to selling point

content/docs/inline-blocks/block-textarea.md
The name of the import is `BlockTextarea` not `BlockTextArea`
=> Fix capitalisation of import

content/docs/fields/custom-fields.md, content/docs/gatsby/custom-fields.md
`class` prop on a div should be `className`
`htmFor` prop on a div should be `htmlFor`
=> Fix custom fields examples

content/docs/nextjs/github-public-repo.md
Add a blurb stating workaround for editing a site in which you own.
fixes #357
=> docs: add blurb stating workaround for editing on the base

content/docs/nextjs/github-public-repo.md
Move filename outside of code blocks, as it can break certain filetypes like json
=> docs: move filenames outside of codeblocks

content/docs/cms.md
- removed outdated `theme` property on sidebar config
- added the toolbar state options to the examples and interface
I think there's room to expand on Toolbar usage in an Inline Editing guides, but for the base documentation I think this works. Perhaps I need to add a sentence as to what the toolbar is?
=> Adds Toolbar Docs

components/layout/DocsTextWrapper.tsx, components/ui/DocsNav.tsx, content/guides/index.md, content/toc-doc.json
- Makes the sub-level nav items in both the docs and guides navs be 'Inter'. I found the Tuner font very difficult to read at this level.
- Adds a min-height on the Docs Text. Since we have so few guides atm, it looked slightly broken with the footer up too close to the content. 
Note that for nav items that don't have children, we need to specifically pass the `isTunerFont` property for this item in `toc.json`. Not ideal but I figure these are the edge cases as most top-level nav items have children.
=> Adjust Docs Nav Submenu Item Font

content/blog/simple-markdown-blog-nextjs.md, content/blog/using-tinacms-with-nextjs.md, content/guides/nextjs/github-open-authoring/initial-setup.md
To put it on Vercel, I had to refactor the plain (without Tina) next.js demo to not use a `src` directory. This updates the first blog, will still need to change the blog that talks about adding Tina.
=> Update nextjs blog

content/docs/contributing/guidelines.md
Since the #dev channel in the linked slack is archived with the reasoning that discussions should now all happen in community.tinacms.org it makes sense to remove the link from the docs.
=> remove link to slack channel from the contributing doc

content/blog/2020-05-19-release-notes.md
It's misleading to refer to this project as "serverless" because it implies our previous solution wasn't serverless (since serverless is now a term with lots of connotation tied to it.)
Furthermore, I wanted to clarify that the main goal is to avoid reliance on vendor-specific behavior; minimizing server-side code is a strategy to help us get there.
=> Change release notes language re: GitHub project

content/docs/inline-blocks.md
When a block is added `_template` comes from the block type, so defining it in the `defaultItem` isn't necessary.
=> remove _template from defaultItem

content/docs/inline-blocks/block-image.md, content/docs/inline-editing/inline-image.md
To reflect changes implemented via [this PR](https://github.com/tinacms/tinacms/pull/1105). These changes should be released next week. They involve breaking changes with the render props and children.
=> Update inline image docs

content/guides/nextjs/adding-tina/project-setup.md
Fixes incorrect URL in Guide: "Add Tina to a NextJS Site" -> should point to tina.org instead of localhost:3000
=> Guides - NextJS/TinaCMS: Fix incorrect URL

content/docs/inline-editing/inline-wysiwyg.md
got an error when I did
```
yarn add react-tinacms-{editor,github,inline}@next
```
I fixed it by switching the import to this. Should we update docs?
=> fix: updated inline-wysiwyg docs

content/docs/fields/blocks.md
When I initially read the docs, I mistakingly thought templates was an array (as did Brent). This is a bit more verbose, but more clear IMO.
Also, '_template' was missing from the example
=> Blocks Docs - clarify template

content/guides/gatsby/adding-tina/add-gatsby-plugin-tinacms.md, content/guides/gatsby/adding-tina/creating-forms.md, content/guides/gatsby/adding-tina/meta.json, content/guides/gatsby/adding-tina/next-steps.md, content/guides/gatsby/adding-tina/overview.md, content/guides/gatsby/adding-tina/project-setup.md, content/guides/gatsby/meta.json
[Preview URL](https://tinacms-site-next-git-gatsby-guide.tinacms.now.sh/guides/gatsby/adding-tina/overview)
This PR migrates the Gatsby docs to being a guide
=> Gatsby guide

content/guides/general/meta.json
Since there's no actual guides there yet it doesn't show up in the sidebar
=> added a "general" guides category

components/layout/Header.tsx, components/ui/DocsNav.tsx
I needed a break from writing guides. So I made the GitHub star count show up again.
=> style: add 5px to github button to show star count

content/docs/fields/blocks.md, content/docs/fields/color.md, content/docs/fields/group-list.md, content/docs/fields/html.md, content/docs/fields/image.md, content/docs/fields/markdown.md, content/docs/fields/tags.md
Restructured field docs to be the table format. The group list and block docs didn't really fit this format the best. let me know what you think.
=> Restructure docs

content/blog/custom-field-plugins.md, content/blog/using-tinacms-with-nextjs.md, content/docs/nextjs/next-tinacms-github.md, content/guides/nextjs/git-based/adding-backend.md, content/guides/nextjs/github-open-authoring/api-functions.md
The hard coded localhost url is not necessary as the currently used base url will be used instead (ie, on localhost:3000 it will use localhost:3000, and on 192.168.2.23:3000 it'll use 192.168.2.23:3000), but by hard coding it TinaCMS will not function if the running instance is accessed from a different url. TinaCMS will then become unresponsive and actually lock up the chrome tab if you attempt to access it that way.
Also removed two instances if `are are` in the documentation text.
=> Docs: Remove duplicated words from docs, and remove hard-coded localhost urls from GitClient config docs.

content/docs/cms.md, content/docs/forms.md
Relating changes from [this PR](https://github.com/tinacms/tinacms/pull/1324). Jump to the[ preview here](https://tinacms-site-next-p6fd1ev7i.vercel.app/docs/forms#customizing-form-buttons).
Not sure if we want to officially deprecate the old sidebar / toolbar buttons options, but I added that note.
=> docs: Adds form buttons docs

content/docs/index.md, content/navigation.json, pages/index.tsx
We rewrote the Docs index to serve as a jumping-off point for people visiting the website. This was inspired by the phenomenal [Django Docs](https://docs.djangoproject.com/en/3.0/) as well as the [Rust-lang learn page](https://www.rust-lang.org/learn)
[Checkout the preview here](https://tinacms-site-next-git-docs-index.tinacms.vercel.app/docs)
=> Docs index

components/layout/MarkdownContent.tsx, components/layout/OpenAuthoringSiteForm.tsx, components/ui/DynamicLink.tsx, pages/_app.tsx, pages/blog/[slug].tsx, pages/blog/page/[page_index].tsx, pages/community.tsx, pages/docs/[...slug].tsx, pages/docs/index.tsx, pages/enterprise.tsx, pages/guides/[category]/[guide]/[step].tsx, pages/guides/index.tsx, pages/index.tsx, tinacms/BlogPostCreator.ts, tinacms/ReleaseNotesCreator.ts, tsconfig.json, utils/shortcodes.tsx
instead of:
```ts
import { Something } from "../../../../../../components/Something"
```
we can now just do
```ts
import { Something } from "components/Something"
```
I only updated the paths that go all the way up to `utils` and `components`. 
This is made possibly by adding `baseUrl: "."` to the `tsconfig.json`.
[See Next.js Docs for details](https://nextjs.org/docs/advanced-features/module-path-aliases)
=> Ts absolute paths

content/docs/ui.md
It's not actually possible to pass functions through gatsby-config options The object gets serialzied to json or something and the function is lost.
=> replaced invalid gatsby example

content/guides/nextjs/github/configure-custom-app.md
Since `props.pageProps.preview` is `undefined` until we set up the preview on the index page (at the next step), the CMS was automatically enabled and this was causing an issue where it wouldn't trigger the auth flow. This more strict check for `undefined` should make this step behave as described — allowing people to confirm their auth via cookies being set.
This change _should_ fix your issue @DirtyF, although it's slightly difficult to test since I didn't go through the guide again from step 1, so let me know.
=> guide: updates cms.enabled at auth step to check for undefined

content/packages.json, content/toc-doc.json, pages/packages/[slug].tsx, utils/docs/getPackageProps.ts
- Add more packages to the website
- Generate metadata using package name instead of always using "Packages"
- Stop rendering H1, let the README do that
- Switched Integrations with Packages in the sidebar
=> More packages

content/docs/plugins/fields/blocks.md, content/docs/plugins/fields/custom-fields.md, content/docs/plugins/fields/date.md, content/docs/plugins/fields/html.md, content/docs/plugins/fields/image.md, content/docs/plugins/fields/markdown.md, content/docs/plugins/fields/number.md, content/docs/plugins/fields/textarea.md, content/toc-doc.json
- Move `date`, `markdown`, and `html` to the bottom of the Plugins Nav
- Remove content of said files and instead link to the appropriate package docs
=> Deprioritize non-default fields

utils/docs/getPackageProps.ts, utils/docs/slugifyToc.test.ts, utils/docs/slugifyToc.ts, utils/getMarkdownFile.ts
fixes #580 
This is the "cheap" fix I suggested in the issue, but likely fits the 80+% use case as underscores seem to be the main problem
I plan in going through the docs front-to-back today, I'm gonna check all the ToC links before merging this
=> fix: generate better slugs in docs ToC

content/docs/cms.md
Noticed that we didn't have a reference for the methods on the CMS. While they're used in examples, I thought a base reference would be helpful.
=> docs: adds cms methods docs

pages/guides/index.tsx, pages/packages/[slug].tsx, utils/docs/getPackageProps.ts
There is a bug in the Vercel builder that is preventing some files from being accessed in preview mode lambdas, causing errors when trying to edit the site. This workaround should solve the problem until they implement a long-term fix.
When the workaround is no longer needed, we should revert `4b085db51c8aa6f3b37b5087dffe154a79adf414`.
=> Temporary fix for file access in preview mode lambdas

content/docs/plugins/fields.md, content/docs/ui/inline-editing.md
- Adds a list of default and external field plugins
- Adds more information on field definitions, the `name` and `component`
- Adds custom inline field example
I wrote these pretty fast. They could use a readthrough.
=> docs: updates field overview

pages/guides/index.tsx
This should make the guides index work correctly when in edit mode
=> trigger Vercel builder to provide all content to lambdas

content/guides/gatsby/adding-tina/next-steps.md, content/guides/gatsby/adding-tina/project-setup.md
Hey!
I was going through the **Adding Tina to a Gatsby Site** and found this typo on *Table of Contents* section.
_A snap from [https://tinacms.org/guides/gatsby/adding-tina/project-setup](https://tinacms.org/guides/gatsby/adding-tina/project-setup)_
**This was just due to a couple extra (`##`) in the markdown file. This is fixed in this PR.**
_A view from my local setup (after the fix)_ 
Thanks for your amazing work, folks! 💙
=> Fix typo in table of contents on gatsby guides

components/ui/BlogPagination.tsx, content/blog/add-and-delete-files.md, content/blog/announcing-tinacms.md, content/blog/creating-markdown-drafts.md, content/blog/custom-field-components.md, content/blog/custom-field-plugins.md, content/blog/deprecating-tina-git-server.md, content/blog/designing-an-extensible-styling-system.md, content/blog/dynamic-plugin-system.md, content/blog/editing-on-the-cloud.md, content/blog/exporting-wordpress-content-to-gatsby.md, content/blog/gatsby-tina-101.md, content/blog/inline-editing-project.md, content/blog/introducing-tina-grande.md, content/blog/introducing-visual-open-authoring.md, content/blog/jamstack-denver-talk.md, content/blog/screen-plugins.md, content/blog/simple-markdown-blog-nextjs.md, content/blog/software-engineering-daily-podcast-tinacms.md, content/blog/three-ways-to-edit-md.md, content/blog/tinacms-ui-whats-next.md, content/blog/upgrade-notice-improved-github-security.md, content/blog/using-tinacms-on-gatsby-cloud.md, content/blog/using-tinacms-with-nextjs.md, content/blog/what-are-blocks.md, pages/blog/[slug].tsx
Pretty much just copied the implementation from the docs template. 
~~If we are okay with this manual approach, I can go through the old blogs and fill in the correct `next` / `prev` frontmatter values. Wanted to get feedback before I went and updated all those. To check this out, it works on the **two most recent blogs**.~~
Updated all fm values.
=> Blog Template: next / prev posts

package.json, yarn.lock
This is normally a significant upgrade, but bumping the version is all that's required for us. This is due to the fact that we're using `react-instantsearch` instead of rolling our own, and the fact that our `createIndices` script appears to be written against the v4 API but fortuitously seems to work well enough on v3
this upgrade is a prerequisite to further work on the search index, so any potential indexing issues will be addressed in a later pull request
=> chore: upgrade algoliasearch to v4

components/layout/MarkdownContent.tsx, content/docs/getting-started/cms-set-up.md
If a fenced code-block has the "copy" tag then it will be copyable. It is this way becase not all code-blocks should be copy-able.
Non-copyable JS
```js
const christmastPresent = new Banana()
```
Copyable JS
```js,copy
const christmastPresent = new Banana()
```
Copyable Text
```copy
Hello World
```
=> if a codeblock's tags contain "copy" then a copy button will be rendered

now.json
=> correct the redirects

components/DocumentationNavigation/DocsNavigationList.tsx, components/DocumentationNavigation/DocumentationNavigation.tsx, components/DocumentationNavigation/NavSection.tsx
This takes the logic @kendallstrautman wrote for auto scrolling to the guides nav section and applies it to all nav items. If a nav link appears more than half way down the nav, the nav will load scrolled to that location when the user is on that page.
=> Nav Scroll

components/DocumentationNavigation/DocumentationNavigation.tsx, components/search/hitComps.tsx, components/search/indices.tsx, utils/docs/getPackageProps.ts
note that only `react-tinacms-github` is currently in the search index. other entries will only start indexing once this is pushed to prod.
=> update package search index when package pages are updated

content/guides/nextjs/adding-tina/adding-tina-provider.md
Hi, I am working through your Next.js guide. While it is very well done, I was quite confused that at the end I don't see any sidebar. Digging further I figured I need to pass a few options to `withTina`, so this is my attempt to fix the documentation.
Note that the guide is still outdated, after I open the sidebar I get a message about Markdown Field deprecation:
=> Next.js guide: Add `enabled` and `sidebar` options to `withTina` 

pages/guides/[category]/[guide]/[step].tsx, utils/open-graph-image.tsx
The new open graph image function didn't support the old single line layout, so docs and guides SEO images weren't showing up. I added support for both layouts to the new function.
=> Open Graph Image Fix

pages/guides/index.tsx
this will fix the 502 error when visiting the guides index in edit mode
=> fix(guides/index): send preview data to getDocsNav

components/DocumentationNavigation/DocsLeftSidebar.tsx
=> fix search results clipping bug

utils/docs/getPackageProps.ts
Until we can invalidate pages via webhook, let's regenerate package docs once per hour. A 24-hour feedback loop for docs updates is too long.
=> Regenerate package docs hourly

.github/workflows/create-indices.yml, .github/workflows/nodejs.yml
github actions should use the [same major version as Vercel](https://vercel.com/docs/runtimes#official-runtimes/node-js/node-js-version)
=> use node 12 in workflow scripts

components/DocumentationNavigation/DocumentationNavigation.tsx, pages/docs/[...slug].tsx
The series of breakpoints used to 'tame' the CSS grid was overly complicated so I've simplified it. The new grid is better at using the space available & balancing the placement of content.
Also, the hamburger toggle was overlapping the content on 'tablet' size, which is now fixed.
Before:
After:
=> fix overlap issue, improve  grid logic

pages/guides/[category]/[guide]/[step].tsx
The previous/next links weren't working for guides pages. It looks like the currentPath had a trailing slash but the individual step slugs didn't. This is a quick fix but probably not the best way to fix this. I'm not sure if the slug format changed or why this was previously working.
=> fix guides pagination

components/DocumentationNavigation/DocsLeftSidebar.tsx
The docs nav header drop shadow was rendering funky in Safari. This fixes it.
=> fix safari transparent color bug

content/docs/plugins/forms.md
`form` is omitted  from the return array but then used on the next line
const [modifiedValues, form] = useForm(formConfig)
usePlugin(form)
=> Fix doc code on useForm

components/inline-wysiwyg.tsx
Given I usee GitHub as a media provider
When I upload an image 
Then I can see it in Edit mode
And I can see it in Production
props @dwalkr
=> fix: image path

utils/docs/getPackageProps.ts
will enable us to document unreleased features as they are created, and they will only show on tinacms.org once released
=> package docs: show from latest release, not master

content/docs/media.md
The first example–adding the store to an existing CMS–as really simple.
The second example–adding the store when instantiating the CMS– was much more complex and had React hook code.
This PR simplifies the second example
=> Update Adding Media Store Example

now.json
redirects all routes under `/guides/nextjs/github-open-authoring` to `guides/nextjs/github`
- https://tinacms-site-next-git-fix-guide-redirect.tinacms.vercel.app/guides/nextjs/github-open-authoring/initial-setup
- https://tinacms-site-next-git-fix-guide-redirect.tinacms.vercel.app/guides/nextjs/github-open-authoring/configure-custom-app/
=> chore: fix guide redirects

content/guides/nextjs/github/configure-custom-app.md
Re: [this forum issue](https://community.tinacms.org/t/github-nextjs-error/368/5), on newer repos the base branch is 'main', not 'master'
=> Add base branch to github example 

content/guides/nextjs/github/configure-custom-app.md
- GithubMediaStore also needed to be imported.
- Also the guide was referencing the old auth cookie, when it should be the csrf_token
=> Added missing import in guide

content/docs/plugins/fields/image.md
Should be merged once [this PR](https://github.com/tinacms/tinacms/pull/1594) is released.
=> docs: adds clearable to image field options

content/docs/getting-started/introduction.md, content/docs/index.md
Changing the language from "Tina is a toolkit for building custom CMSs", to "Tina is a toolkit for building visual editing into your site".  
Feedback from interviews done with developers in the past indicated that people were confused by the idea of building a custom CMS.  When they think of a CMS, they picture something like WordPress and are not interested in building that.
=> Change language in docs 

content/docs/ui/inline-editing.md
Address feedback from @logan-anderson 
Reference: https://github.com/tinacms/tinacms/blob/master/packages/react-tinacms-inline/src/fields/inline-text-field.tsx#L34-L39
=> fix: InlineTextField is deprecated

content/docs/plugins/fields/toggle.md
No biggie, but tripped up the olde copy n' paster
=> FIX: typo in component name in code example

content/docs/ui/inline-editing/inline-group.md
The example code on the [InlineGroup docs](https://tina.io/docs/ui/inline-editing/inline-group/) was [missing two commas](https://github.com/tinacms/tinacms.org/pull/772/files#diff-def6a26f6e603e530b7dfadc41350b7062e4cb3ca3971dbeb2e5e3a82d5a9104R43-R44).
I edited and committed through the TinaCMS interface on the website. Apparently, this caused other formatting changes to the code. Would you like me to revert those?
=> Fix syntax error in inline editing example

content/pages/home.json
The Netlify team decided to drop the acronym, it's now written Jamstack, not JAMstack.
source: https://jamstack.org/
=> fix: Jamstack

content/docs/contributing/setting-up.md
Adding documentation to assist users who want to contribute to the tina project, commenting on how to run a tina development environment, so that they can make changes to the repository packages and test the changes to the demo packages.
=> Adding documentation to run development in Tina

now.json
404 on https://tina.io/docs/getting-started/how-tina-works/ 
linked from:
- https://jamstack.org/headless-cms/tinacms/
- https://github.com/TryGhost/nodecmsguide/blob/master/content/projects/tinacms.md 
note: we'll need to update those descriptions, as they are amongst our best referrers.
=> Fix 404 from jamstack.org

content/guides/nextjs/adding-tina/creating-forms.md
`rawMarkdownBody` does not exist on initialPost. As described in project setup, `post.content` contains the raw markdown.
=> Replace rawMarkdownBody with content in the nextjs guide

content/guides/nextjs/github/hosting-vercel.md
Noticed the "How does this work?" ToC item on this page:
https://tina.io/guides/nextjs/github/hosting-vercel/
is broken.
Looks like top-level ToC items need to start at `h2` (`##`) in order to render proper markdown (this started at `h3` or `###`).
=> fix(hosting-vercel): Fix TOC

content/docs-navigation.json, now.json
=> fix: docs navigation

content/docs/plugins/screens.md
The 'Example use cases' section contained an example use case with a minor typo.
=> Minor wording/ spacing fix for 'Screens' documentation

components/home/Actions.tsx, components/home/Browser.tsx, components/home/Navbar.tsx, content/docs/plugins/fields/date.md, public/consumers.json
Because the `DateFieldPlugin` is being moved back into core, we're not longer suggesting users add the `react-tinacms-date` package.
I've moved the README for that package into the core docs, formatted similarly to other field pages.
**Developer's Note:**
`_app.txs` and `package.json` for this repo currently use the `react-tinacms-date` package.  I wasn't sure if it should be part of this PR or not, but we'll want to remove those dependencies once TinaCMS Core has the `DateFieldPlugin`.
Closes https://github.com/tinacms/tinacms/issues/1808
=> Updates docs for DateFieldPlugin

content/docs/tina-cloud/cli.md
This fixes #870 
The schema for the authors section of the defineSchema is missing an s in the name element which causes an error and without prior knowledge is friction for a new user of Tina Cloud .
=> docs: Fixing schema to make docs usable if you follow along

content/toc-doc.json
This adds the 'Quick Start Guide' (Tine Cloud Starter Guide) to the docs index sidebar to further emphasis it as an easy path for new users.
The next step is to move the guide so it's not in the guides section, and the '<- Guides Index' link becomes a link back to the docs index. Given our template structure I'm not sure how to accomplish this with minimal code duplication; input would be great!
=> add quick start guide to doc toc

content/docs/fields.md
Resolves 404 errors on all field plugin links on `https://tina.io/docs/fields/` page.
**Changes:**
- Update to all field plugin URLs in `content/docs/fields.md`
**Additions:**
- None
**Removals:**
- None
closes #890
=> Fix field plugin urls on fields docs page

content/blog/announcement-tina-cloud-is-officially-in-alpha.md
Use a non-expiring invitation link for Tina Cloud Discord, the one we added is expired.
=> fix: Discord link

content/docs/tina-cloud/cli.md
Fixed the example query to show the correct name of getPostDocument and adding where the data is available via localhost:4000.
=> Fixes and improvements for tina cli docs.

content/guides/tina-cloud/starter/structure.md
Make it easy to learn more about `defineSchema`.
On a side note, a documentation reference would be nice, even if you get some autocompletion on types in VSCode.
=> guide: add link to CLI docs 

content/guides/tinacms/getting-started/backends.md
Fix a broken link in getting started tutorial to loading states, blocks, and markdown.
There is still one remaining broken link ```[Inline Editing](/guides/general/inline-blocks/overview)``` which I do not know where to point it to. Maybe: https://tina.io/guides/experimental/inline-blocks/overview/ ?
=> Fix: Broken link to loading states

content/docs/plugins/content-creators.md
**This should be merged in tandem with https://github.com/tinacms/tinacms/pull/1855**
Due to recent changes mentioned in https://github.com/tinacms/tinacms/pull/1855, `ContentCreator`'s options more closely align with those provided to any `useForm()` variant.
I've updated the docs for `ContentCreator` to match the new interface, copying the details for the new options from the `Form` documentation (so they match).
Closes #911
=> Updates documentation for ContentCreator

content/docs/cms.md, content/docs/media.md
We are switching the media library UI from numbered pagination to "cursor-based", where the only controls are buttons to move forward and backward in the list. This is a **less-opinionated** approach and makes the media library compatible with asset managers like Cloudinary, which don't give you arithmetical control over the entire collection but instead provide a cursor that allows you to navigate further into the set.
This is a **breaking change** for users with custom media stores. They will need to update their media stores to satisfy the updated interfaces. These changes should be trivial, and I will be writing a brief upgrade guide to be added to the release notes when the updates are published. Users that are using the first-party `GithubMediaStore`, `GitMediaStore`, …
=> Update Media APIs for tinacms/tinacms#1859

content/packages.json, content/toc-doc.json, utils/docs/getPackageProps.ts
Adds links to the ```next-tinacms-cloudinary``` package to the Tina docs
=> chore: add documentation links for next-tinacms-cloudinary

components/layout/DocsLayout.tsx, content/docs/tina-init-tutorial.md, pages/docs/[...slug].tsx
This is the getting started tutorial for Tina init.
This will not be linked on our site but will be used in an i frame in the users app. 
Link: https://tinacms-site-next-git-feat-tina-init-tutorial-tinacms.vercel.app/docs/tina-init-tutorial/?layout=false
This also adds the ability to remove the layout when in the docs with a query param. (tina.io/docs/some-doc-page/?layout=false). This will only render the doc page and not the nav, header, footer, etc.
=> added tina-init-tutorial.md

content/toc-doc.json
In the Tina Cloud section of the docs, the sidebar had dropdowns that contained in page links (not inter page links) - the same links that were already present on the Table of Contents on the right hand side of the page. 
To keep consistent, removed in page links on the sidebar. Looks a little too sparse now in my opinion but we might gain more hierarchy once we work on more Tina Cloud docs.
=> remove inpage links on sidebar for cloud section

content/docs-navigation.json, content/navigation.json, content/pages/cloud.json, content/pages/home.json
Remove 'Guides' from site navigation. Will rework Docs section to include Guides subsection.
=> Remove 'Guides' from root navigation

content/blog/tina-cloud-a-headless-cms-backed-by-git.md, content/guides/tina-cloud/existing-site/page-preview.md
We were linking to old deployment previews. This caused me to take a bit of a detour and browse the wrong set of docs :)
=> Remove links to Vercel previews

content/docs/index.md
Moving Links that are no longer "Tina Cloud" and are TinaCMS toolkits.
=> Moving links and renaming some options

content/guides/tina-cloud/starter/connect-to-tina-cloud.md, content/guides/tina-cloud/starter/local.md
Walkthrough led me to a few snags, I've updated the starter in [this PR](https://github.com/tinacms/tina-cloud-starter/pull/127) to address them from that end.
Our change to use `.env.development` is related to most of these updates
=> Make some changes to the walkthrough after going through it

content/pages/cloud.json
... and make @mittonface happier
We're changing the way people signup on Tina Cloud, you should now use https://app.tina.io/register.
=> Point to the new register link on homepage

content/docs/tinacms-reference.md
- Fix a 404
- Use text links instead of generic "learn more" links for better a11y.
=> docs: API reference overview

components/layout/DocsTextWrapper.tsx, components/styles/GlobalStyle.tsx
This uses [code from this CodePen](https://codepen.io/chriscoyier/pen/YzXeXjK) to automatically wrap videos with a responsive container that adapts to the video's aspect ratio (thanks @DirtyF!). 
This is one of a couple issues breaking the mobile layout. The other issue has been addressed in the design update PR.
closes #898
=> Mobile Video Fix

pages/guides/[category]/[guide]/[step].tsx
closes #879 with changes described on that issue
=> Improve Guide Nav Hierarchy

content/guides/tina-cloud/starter/meta.json, content/toc-doc.json
Update guide headings, as the starter guide name was misleading
=> docs: Update headers on tina guides

content/docs/tina-cloud/faq.md, content/toc-doc.json
Add in FAQ section to Tina Cloud Docs.
- Carried over relevant 'Alpha FAQ' info
- Added in section for hanging logging in screen
- Can continue to add to this section as running list of cloud FAQs instead of release specific.
=> Add in FAQ section

content/blog/announcement-tina-cloud-is-officially-in-alpha.md, content/docs/tina-cloud/alpha-faq.md, content/docs/tina-init-tutorial.md, now.json
We're now in beta, our default URL has changed to app.tina.io
@jamespohalloran can we just call it Tina Cloud FAQ instead of Alpha FAQ?
=> fix: alpha to beta

content/docs/media-cloudinary.md
While dogfooding, I encountered an error message when implementing the Cloudinary MediaStore locally (clientId is `null`).
Fortunately, I knew this was being triggered by the `authorized` method and just had it return `true`.  But, I thought it might be best to only short circuit `authorized` when local (and preserve the test otherwise).
This simply changes the suggested code snippet when setting up the API routes.
=> Adds LOCAL_CLIENT check to Media Cloudinary

content/guides/tina-cloud/starter/overview.md
When a user clicks "quickstart" form the home page, give them an option to start locally, rather than having to sign up. 
I thought the create-next-app approach might work better than a clone / install / yarn dev approach, because when the user eventually connects to Tina Cloud, they can just push up what they have rather than needing to change the remote from tinacms/tina-cloud-starter to <users-account>/tina-cloud-starter.
=> docs: Add command line quickstart option

content/guides/tina-cloud/starter/overview.md
We don't have a link in the starter to the admin page, so I added a blurb here to give the user context to start editing
=> docs: Add admin context to CLI getting-started

content/docs/tinacms-context.md
Mitch pointed out that the example usage of `getStaticPropsForTina` in the documentation is not correct.
More than likely, a change was made to its usage and the documentation was not updated.
=> Updated `getStaticPropsForTina` usage in Docs

content/docs/tinacms-context.md
We have a section for "extending Tina" where this content already lives
=> docs: Remove faq from contextual editing doc

content/docs/features/data-fetching.md, content/docs/schema-advanced.md, content/guides/tina-cloud/add-tinacms-to-existing-site/markdown-plugin.md, content/guides/tina-cloud/add-tinacms-to-existing-site/next-changes.md, content/guides/tina-cloud/starter/structure.md
Partially addresses https://github.com/tinacms/tinacms/issues/2108 (We still would need to update a few other docs, and update our starter, but wanted to push this up to get opinions.)
As noted in that issue, I think having a separate API for talking to our content-api within getStaticProps vs getStaticPaths adds unnecessary complexity. I feel like using the `staticRequest` function within getStaticProps & getStaticPaths reads better, but thoughts?
https://tinacms-site-next-git-rm-getstaticpropsfortina-tinacms.vercel.app/docs/features/data-fetching/
=> docs: remove getStaticPropsForTina from intro doc

content/blog/tina-cloud-a-headless-cms-backed-by-git.md, content/docs/tina-cloud.md, content/docs/tina-cloud/dashboard.md, content/docs/tina-cloud/faq.md, content/docs/tina-cloud/using-app.md, content/guides/tina-cloud/add-tinacms-to-existing-site/deployment.md, content/guides/tina-cloud/starter/connect-to-tina-cloud.md, content/guides/tina-cloud/starter/create-account.md, content/toc-doc.json
Change references from 'Apps' to 'Projects' when referencing the Tina Cloud dashboard.
=> Change references from Apps to Projects

components/DocumentationNavigation/DocumentationNavigation.tsx, components/DocumentationNavigation/VersionSelect.tsx
Add a version select dropdown, so that users will be able to browse older site deployments.
This will allow us to have a cleaner split between the "legacy" docs, and the current promoted path on tina.io
TODO:
=> Add version select

content/pages/home.json
There is a Vercel bug being exposed from within the quickstart, where the framework is being set to "other".
The Vercel team has been investigating, but it could have a big impact on the user's first experience. I'm proposing (for now) we instead direct them to the docs path instead of the quickstart from our main CTA
=> Change main CTA to docs

components/search/indices.tsx, data-api/fetchBlogs.ts, indices/createIndices.ts, pages/rss.xml.tsx
- Remove package docs from search results
- Only index new packages 
We were showing a lot of irrelevant info in the search results, which I suspect may have lead people to outdated paths
=> Remove outdated content from search

now.json
It seems many of these redirects aren't working without a trailing slash
=> add trailing slashes to legacy redirects

content/blog/add-and-delete-files.md, content/blog/creating-markdown-drafts.md, content/blog/editing-on-the-cloud.md, content/blog/exporting-wordpress-content-to-gatsby.md, content/blog/gatsby-tina-101.md, content/blog/inline-editing-project.md, content/blog/introducing-tina-grande.md, content/blog/more-changes-coming-to-inline-editing.md, content/blog/three-ways-to-edit-md.md, content/blog/using-tinacms-on-gatsby-cloud.md, content/docs/legacy-redirect.md, data-api/fetchBlogs.ts, pages/blog/[slug].tsx, utils/blog_helpers.test.ts, utils/blog_helpers.ts
Show a banner on old posts redirecting to new docs
A few posts had a banner as shortcode, but I moved it to metaData so that we can apply defaults without having to worry about double banners
One very popular post that still gets a lot of traffic is https://tinacms-site-next-git-outdated-post-banner-tinacms.vercel.app/blog/simple-markdown-blog-nextjs so this should mitigate that.
fixes #1054
=> Outdated post banner

components/cloud-beta-disclaimer.tsx, content/blog/tina-is-in-beta.md, content/docs/index.md, content/pages/home.json
- Change our guides CTA's to link to either the main docs setup, or the quickstart
- Change the main hero button to link to the quickstart, now that Vercel has fixed the framework:other issue
=> Update main cta links

content/docs/tinacms-context.md
We've changed `/admin` for both `tina-cloud-starter` and `tinacms init` and wanted to update the documentation to reflect that.
`/admin` will now take the user to a log in page.  `/exit-admin` has been replaced by `/admin/logout`.
This new page is also an easy gateway to using `TinaAdmin` should a user be interested in doing that (but I chose to leave that out of the docs for now).
Closes #1116
=> 1116 - Updates docs for TinaCMS Context regarding `/admin`

content/docs/setup-overview.md
Right now, we're managing 2 paths within the intro doc, and it's a big hard to navigate where to send the user next. 
I think by sending users who already have a site to a specific guide, we can better segment users.
=> Link to guide for tina init

components/home/Features.tsx, content/docs/setup-overview.md
Ensure npx create-tina-app specifies "latest" since NPM caches will store older versions
cc @jamespohalloran - we've had issues in the past with `npx` commands, we should always specify `npx whatever@latest`
=> Specify "latest" on npx command

components/DocumentationNavigation/DocsHeaderNav.tsx
instead of linking to quickstart in header, link to "getting started" hub in header. This page should give all users context on how to make commits, and next steps.
=> Link to "getting started" hub in header

components/home/Actions.tsx, components/home/Features.tsx, components/home/GlobalStyles.tsx, components/layout/MarkdownContent.tsx, content/docs/setup-overview.md, content/pages/home.json
Update homepage so that:
- Homepage has CLI CTA on main section
- Fix the "Command Line" section that shows both `create-tina-app` and `@tinacms/cli init`
A couple things before we merge:
=> Update create-tina-app homepage CTA's

package.json, pages/api/graphiql.ts, yarn.lock
There was an error for `addPendingDocument` that's showing in the GraphiQL playground that we've fixed in the latest version.
=> Update graphql playground to use latest version

components/search/hitComps.tsx, indices/createIndices.ts
Fixes #1044 
Back in #617 a change was made so that we only indexed the first 200 characters of a doc. My best guess is that this was to make things less ugly when searching. 
This change switches things back to index the entire doc, but on the search side of things we use algolia's `<Snippet/>` functionality which I've configured to only display 50 words no matter how long the doc is.
Let me know if 50 words is too many or if you remember there being some other reason for the change in #617
=> docs: index whole document, use snippets in search

content/docs/tina-cloud/connecting-site.md, content/docs/tinacms-context.md, content/guides/tina-cloud/add-tinacms-to-existing-site/markdown-plugin.md
We should try and use Vercel's system environment variables if available to populate the TinaCMS config. Most people will set Tina up on a branch initially rather than main, so this allows the user to forget about manually setting/switching branches in code
=> Pull vercel env for our branch config

content/docs/tina-cloud.md, content/docs/tina-cloud/dashboard.md
Wanted to link from somewhere from the [LocalMode sidebar banner](https://github.com/tinacms/tinacms/pull/2354) where we can compare/constrast local-mode vs prod-mode.
Some of the content in the overview was a bit dated (It talked about the content-api as if it was a separate feature for Tina Cloud compared to tinacms), and a lot of this content has already been covered in the new GraphQL sections
=> docs: add blurb constrasting local-mode prod-mode

components/home/Features.tsx, content/pages/home.json
Change our references from tina init to create-tina-app to keep onboarding consistent. 
Also updated the text in our main header as per @scottgallant 's suggestion
=> Update homepage CTA/hero

content/docs/schema.md
- Split out blocks from intro doc (Seems a bit advanced for the avergae starting use-case)
- Link to reference field-types
=> Simplify content modelling

content/docs/features/data-fetching.md
I was a bit torn on including this, as it uses useGraphqlForms instead of staticRequest, however I hope that the warning banner covers our bases. 
I don't think we gave enough context before that the queries, were based off of the defined schema. Probably more that can be done here, so I'm open to ideas!
=> Add playground to data-fetching doc

data-api/fetchDocs.ts, indices/createIndices.ts
Remove any content within toolkit or releases from search.
(I wanted to add some tests around this, but it's tricky to test the fast-glob package). I tested the path locally, and it correctly removed the 17 reference pages
=> remove releases & toolkit content from search

components/cloud-beta-disclaimer.tsx
This documentation is fairly far along in the onboarding path. We're also linking to this section from the local Tina sidebar, so it probably makes more sense to funnel the user to import a repo, rather than using the quickstart
=> Link to registration page from beta cloud banner

content/docs/tina-cloud/connecting-site.md, content/docs/tinacms-context.md, content/guides/tina-cloud/add-tinacms-to-existing-site/markdown-plugin.md
This API definitely feels better, but it's still a bit awkward when using the environment's branch. Did my best to offer some docs [on that](https://tinacms-site-next-git-use-api-url-tinacms.vercel.app/docs/tina-cloud/connecting-site/#using-the-deployment-branch), any insight welcome!
Goes with this PR https://github.com/tinacms/tinacms/pull/2377
EDIT: I've updated things so that the client id isn't stored as an env var. Maybe that helps a bit.
cc @jamespohalloran
=> Use apiURl prop

content/docs/reference/toolkit/fields.md, content/docs/reference/toolkit/fields/blocks.md, content/docs/reference/toolkit/fields/color.md, content/docs/reference/toolkit/fields/date.md, content/docs/reference/toolkit/fields/group-list.md, content/docs/reference/toolkit/fields/group.md, content/docs/reference/toolkit/fields/html.md, content/docs/reference/toolkit/fields/image.md, content/docs/reference/toolkit/fields/list.md, content/docs/reference/toolkit/fields/markdown.md, content/docs/reference/toolkit/fields/number.md, content/docs/reference/toolkit/fields/radio-group.md, content/docs/reference/toolkit/fields/select.md, content/docs/reference/toolkit/fields/tags.md, content/docs/reference/toolkit/fields/text.md, content/docs/reference/toolkit/fields/textarea.md, content/docs/reference/toolkit/fields/toggle.md
Add alert indicating the toolkit field reference may not be what the reader is after
Closes https://github.com/tinacms/tinacms.org/issues/1118
=> Add alert to toolkit field references

content/docs/features/data-fetching.md, content/docs/migrations/upgrading-to-usetina.md
Adding a helper doc for migrating to 0.63
Explaining:
- useTina
- apiURL
I don't know if we currently have a great place for this type of doc, but I planned on sharing in the releases channel in Discord
=> Document migrating to 0.63

pages/community.tsx
This removes Tina from the community page. It's still using `getJsonPreviewProps` utility, which uses the `next-tinacms-github` package. We can load the `.json` file directly and bypass this, but I wasn't sure if we wanted to do that or not.
=> remove tina from community page

components/home/Blocks.tsx, components/home/Features.tsx, components/home/Flying.tsx, components/home/Hero.tsx, pages/index.tsx
This removes inline components from the homepage and adds a blocks renderer that replaces the `InlineBlocks` component from Tina. 
I'm not really sure how `getJsonPreviewProps` works or what it's doing; if someone would like to assist I'd appreciate it 🙏  
closes #1213
=> remove inline tina from homepage

content/docs/tina-cloud/faq.md
This adds an FAQ item for troubleshooting the `Unable to find record '.tina/__generated__/_graphql.json'` errors that have been occurring. It is accompanied by https://github.com/tinacms/tina-cloud/pull/1374 which is should bubble up these errors to the browser to allow the user to understand better what is happening.
=> add FAQ item for record not found errors

content/docs/reference/types/rich-text.md
Adds a section on how to enable the experimental version, and the playground that uses it https://tinacms-site-next-git-add-rich-text-experimental-tinacms.vercel.app/docs/reference/types/rich-text/#experimental-update
=> Add rich-text experimental docs

content/docs/errors/esbuild-error.md
This adds an error message for the new esbuild feature. Since it is not linked to from anywhere on the site it is save to merge before the feature is released.
=> added an error message for esbuild

content/blog/syntax-highlighting-with-tina.md
This removes an Extra T from the timestamp that causes the API shoutout to show.
=> Remove double T causing issue.

content/docs/editing/blocks.md
This adds a gif for the visual block selector in the docs.
=> Add Visual Block Selector Gif

content/blog/tina-cms-get-started.md, pages/blog/[slug].tsx
The move to MDX (https://github.com/tinacms/tinacms.org/pull/1262) required updating all blog posts with HTML in them. That branch didn't include a couple of more recent posts, and so those weren't migrated. This is causing builds on master to fail now, in a way that wasn't caught in the PR build.
=> MDX compat: 'tinacms get started' post

content/docs/editing/active-field-indicator.md
Current link is directing to the Automated GraphQL SDK #2249 discussion when it should be Active field indicator #2250.
=> Update active-field-indicator hyperlink

content/docs/graphql/read-only-tokens.md
Fix code example, where we weren't getting the JSON from the readonly token fetch response.
Thanks @llibdude for uncovering this!
https://github.com/tinacms/tinacms/discussions/2671
(Sorry about all the formatting updates. The actual change is [here](https://github.com/tinacms/tinacms.org/pull/1288/files#diff-a9dddff0cb83525cf13b8fefac785a71320d69480bb2f1ee4c6e63ce5f1ca470R184))
=> docs: fix readonly token code example

content/docs/cli-overview.md, package.json
- add optional parameters section to the cli-overview
- add engines >= 14 to the package.json since next-sitemap requires node >= 14
=> doc: document init cli options including new --schemaFileTypes

content/docs/tina-cloud/data-layer.md
quick update to the tina-cloud data layer doc to remove the "coming soon" verbiage and link to the data query pages
=> doc: update tina-cloud data layer page to latest status

content/guides/tinacms/non-react-based-ssg/guide.md
The SSG guide broke recently with the changes to extending tina (where you now have to pass schema into tina). I pinned tina to an older version for now.
=> docs: make ssg agnostic from hugo

content/docs/graphql/queries/advanced/filter-documents.md, content/docs/graphql/queries/advanced/limitations.md, content/docs/graphql/queries/advanced/pagination.md, content/docs/graphql/queries/advanced/performance.md, content/docs/graphql/queries/advanced/sorting.md, content/docs/graphql/queries/query-documents.md
This makes it more explicit that the data layer cli flag must be enabled for the advanced query capabilities
=> doc: explicitly mention cli flag and link to doc on all data layer query pages

content/docs/graphql/queries/advanced/sorting.md
Accidentally left http://localhost:3000 in the graphiql example for multi-column sorting
=> doc: remove host from sorting example

content/docs/reference/types/object.md, content/docs/reference/types/string.md, content/docs/schema.md
Our playgrounds are pretty heavy browser loads, so pages that feature multiple playgrounds should instead link to external pages
=> move playgrounds to external links

content/docs/tinacms-context.md
Looks like the only place where `.sys` was still mentioned, updated to `._sys`.
Closes https://github.com/tinacms/tinacms.org/issues/1334
=> Change sys to _sys in RouteMapper docs

content/docs/reference/types/reference.md
Describes what the `reference` field is and includes an example of how to use it.
Before:
https://tina.io/docs/reference/types/reference/
After:
https://tinacms-site-next-git-feat-1330-improves-reference-docs-tinacms.vercel.app/docs/reference/types/reference/
Closes #1330
=> Improves reference docs with example

content/docs/extending-tina/custom-field-components.md
Show an example of using wrapFieldsWithMeta to render out the consistent field label & description
=> Show wrapFieldsWithMeta example

content/docs/cli-overview.md, content/docs/tina-cloud/data-layer.md
**Needs https://github.com/tinacms/tinacms/pull/2919 is released**
With `waitForDB`, we've added one new command `server:waitForDB` and a new option `--dev`.
https://tinacms-site-next-git-feat-add-info-about-waitfordb-cmd-tinacms.vercel.app/docs/cli-overview/
Closes https://github.com/tinacms/product-roadmap/issues/156
=> Adds info about `waitForDB` command to `cli` overview

content/docs/reference/types/reference.md
- See the discord discussion here: [Temporary work around](https://discord.com/channels/835168149439643678/991115358796775526/991464165506039981)
- See the original suggestion for the workaround raised by logan-anderson in this pull request: https://github.com/tinacms/tinacms/issues/2056
- See the following error page related to the fact images don't yet support the `list: true` option: https://tina.io/docs/errors/ui-not-supported/
- that was added via PR #1038 
To provide some extra context and a potential solution to the info banner that explains `list: true` is not currently supported on reference fields (at least, not in the frontend form UI)
=> [Docs update] Suggest workaround to create a list of references

content/docs/reference/config.md, content/toc-doc.json
This is sort of in flux, but might be needed to help non-NextJS users with static mode
[see doc](https://tinacms-site-next-git-add-config-reference-tinacms.vercel.app/docs/reference/config/)
=> Add config reference

content/docs/introduction/tina-init.md
The code sample is missing the quotes around the import.
=> Fix typo in Adding Tina to an existing NextJS site

components/cloud-beta-disclaimer.tsx, content/docs/tina-cloud/dashboard.md, content/docs/tina-cloud/dashboard/organizations.md, content/docs/tina-cloud/dashboard/projects.md, content/docs/tina-cloud/dashboard/users.md, content/toc-doc.json, pages/docs/[...slug].tsx
Update our tina cloud docs now that we've shifted user management to be per-project
=> Project-based-users

content/docs/graphql/queries/advanced/sorting.md
Previously this wasn't specifying the field on the collection ('indexes')
=> add more context to the multifield index definition example

content/docs/reference/media/external/s3.md
Change `TinaCloudCloudinaryMediaStore` to `TinaCloudS3MediaStore` given this code snippet is for the S3MediaStore
=> [docs] Fix typo in example code for S3MediaStore

components/blocks/FAQ.tsx, components/blocks/FeatureGrid.tsx, components/blocks/LogoGrid.tsx, components/blocks/Pricing.tsx, components/blocks/RecentPosts.tsx, components/blocks/RoadmapGrid.tsx, components/blocks/Social.tsx, components/layout/CloudBanner.tsx, components/layout/Footer.tsx, components/layout/Navbar.tsx, components/layout/Section.tsx, components/ui/Button.tsx, pages/404.tsx, pages/blog/page/[page_index].tsx, pages/community.tsx
A number of small styling improvements, mostly adding whitespace. Adds a line for the last item on a roadmap that fades out, improves pricing table styles, fixes issues with padding on the blog page.
=> improve whitespace, roadmap

content/docs/product-tour.md
On https://tina.io/docs/product-tour/ you can see that there is an issue with how the markdown is formatted. This fixes that issue.
Old
New
=> fix issue with markdown format

content/toc-doc.json
| <img width="258" alt="image" src="https://user-images.githubusercontent.com/11611397/207047043-fb4e82ed-aee1-4c54-9881-579180c22d8f.png"> |
|---|
"Overview" menu of "Going To Production" is duplicated
=> Remove duplicated `Overview` link

README.md
It looks like `yarn develop` command is gone and replaced by `yarn dev` since https://github.com/tinacms/tina.io/commit/17246f0b43313b44fada50c2afe36f65bb88ec8c
=> yarn develop -> dev

.tina/config.ts
Looks like some leftover from the refactoring that moved the schema to its own file.
=> Removes unused `defineSchema` import

content/docs/extending-tina/custom-field-components.md
Fixed a typo that was causing a link on the [Custom field components documentation page](https://tina.io/docs/extending-tina/custom-field-components/) to lead to a 404.
=> fix: Update link to the format-and-parse doc

content/docs/forestry/common-errors.md
I think we can skip this once the skip client config lands. Depends on https://github.com/tinacms/tinacms/pull/3734
=> Remove common errors section relating to noSDK option

content/docs/forestry/migrate.md
Not sure if it's a common issue, however, following the steps outlined in **Migrate from Forestry** page, `build` command is necessary and matches provided screenshot.
=> Update build commands on Forestry's migration page

content/docs/tina-cloud/connecting-site.md
Update the GItHub pages docs so that we don't instruct user to build tinacms admin locally
=> GitHub pages docs

content/docs/editing/quick-editing.md, content/toc-doc.json
https://tina-io-git-quick-edit-tinacms.vercel.app/docs/editing/quick-editing/
FYI This leaves out a couple of things:
A bit about the `data-tina-field-overlay` support, the starter doesn't have a good need for it so it's hard to demonstrate
The Vercel preview docs for now, that probably is best to just live as a README in the monorepo.
=> Quick edit docs

content/docs/tina-folder/overview.md
Update docs from old system where __generated__ needed to be pushed to git, to the new system with the tina-lock.json file
=> Update tina-lock docs

content/docs/tina-folder/overview.md
This issue tripped me up when I did a manual conversion from `.tina` to `tina` directory (I did miss the memo). As you can see, the `__generated__` folder states that it can be ignored by Git, but then some of it's subfiles state that they _must_ be commited. Looks like that's just out of date from the old model with a `.tina` directory.
Additionally, a bunch of the items underneath the items which were actually wrong specify that they do not need to be checked into source control. I went ahead and removed those as well for consistency.
=> Correct docs notes for generated items

content/docs/reference/media/external/authentication.md, content/docs/reference/media/external/cloudinary.md, content/docs/reference/media/external/do-spaces.md, content/docs/reference/media/external/s3.md
Improve docs for non-next external-media implementations.
One thing to confirm, I removed the NEXT_PUBLIC_ prefix from our environment variables. It doesn't look like these variables are refenced in the tinacms packages, and I don't believe they are needed on the frontend, but could use a second look just to confirm I'm not missing something.
=> docs: Improve docs for non-next external-media

content/blocksPages/showcase.json
The [Lighthouse](https://wearelighthouse.com) reference in the [ManyHands](https://wearemanyhands.com) spotlight on the [Showcase](https://tina.io/showcase/) page repeats the phrase `design agency based in London`:
> The event (and website) is by [Lighthouse](https://wearelighthouse.com/), a specialist UX and UI  
> _design agency based in London_ **design agency based in London**.
This fix removes the duplicate content.
=> Remove redundant content from Many Hands showcase

content/docs/frameworks/hugo.md
The docs say to run `npm run tinacms build` which leads to a failure as it's the wrong command. Instead the command `npx tinacms build` works on Netlify, given the example.
=> Fix hugo.md incorrect NPM command

content/docs/tina-cloud/branching.md
The url before is localhost:3000 which may be caused by human error
=> fix: point to correct url for config references

components/blocks/FeatureGrid.tsx
This resolves an overlap that's occurring on pages uses the Hero template. Resulting Overlap is presenting anything below the overlap from being intractable. For example, a button from being used. It also poses accessability issues due to text not being copyable..
I've checked the Home page for any issues as a result of making these change and didn't spot any. I'm not familiar with your overall usage however so I may be missing something on other pages. I did not note any visual differences from lowering it to `z-0`. `z-0` is required for the SVG to display correctly so removing the z-index overall isn't an option.
To replicate this issue
- Open a browser window that has a viewport of at least 1920px.
- [view the Forestry.io page](https://tina.io/forestry/)
- Click the Tiny Migration …
=> Resolve Feature Grid Button Overlap

content/docs/reference/self-hosted/auth-provider/bring-your-own.md
Using Tina v1.5.28 authProvider expects async functions but the sample code doesn't have them marked async resulting in type errors
=> docs: mark CustomAuthProvider methods async to fix type errors

components/blocks/Actions.tsx
As per @adamcogan , @sethdaily and @bradystroud #1780  was created to fix the styling of the CTA buttons added to the homepage
**Changes**
- Buttons now sit on new lines 
- 'or' text between the buttons and the npx command
=> CTA Styling 

components/blocks/Actions.tsx, components/ui/Button.tsx
As per #1786 i am assigning ids for each action so that we can track them in Google Tag Manager.
We have also modified the logic to do with action lists so that the list styling applied to the CTA buttons do not ruin the formatting of the rest of the site. This is so that groups of action buttons > 2 will be stacked vertically rather than horizontally.
=> Adding Ids on Action Blocks for Google Tag Manager

components/blocks/Actions.tsx
One of the buttons were not tracking in GTM, this is because the id was being set wrong.
=> XS | Changed ID setting logic for GTM purposes

components/blocks/Actions.tsx
One of the google tags was failing to fire... turns out its because the id needed to be in the lowest mode field (i.e the span) of the CodeButton.
=> Locate gtm error

utils/getExcerpt.ts
As per #1798 the blog posts were not including text that was not of type 'text'. Therefore all text of type <a> was being dismissed. This change modified the `getExcerpt` method used to retrieve text from posts, making sure we include anchored text and map it to text.
**Figure: After the change has been implemented, <a> text now appears**
=> checking more types of text in payload

components/blocks/FeatureGrid.tsx
As per #1802 we have added id's to the feature boxes so that we can collect data for user traffic through their redirect links, this will be useful for marketing teams and to compare to future implementations
=> Feature Grid Id for GTM 

components/blocks/Actions.tsx, components/blocks/Features.tsx
Email thread: ‼️Urgent - Tina.io Homepage - Safari issue
cc: @levijacksonssw
Tailwind gap rendering was behaving differently on safari, causing for the landing page containers to be overlapping - this pr addresses this issue by;
**Figure: ❌ Overlapping image on safari** 
**Figure: ✅ Safari view (from this PR) with fixed spacing** 
_Note that this does make the google chrome sizing (which was test passed) slightly different_
=> 💄🔨 Fixed Sizing on Safari

content/navigation.json
cc: @landonmaxwell 
As per email 🦙Tina.io - Resources - subheadings
(checked by Josh)
Hi Josh,
As per our conversation, the menu items in the Resources dropdown on the nav bar do not match the order on the Resources in the footer.
Please change the nav bar order to match the footer order:
BLOG
EXAMPLES
ROADMAP
SUPPORT
=> 💄 Nav Bar Resources Dropdown item re-order

components/layout/Layout.tsx, components/layout/Navbar.tsx
as per #1851 we reverted my previous fix to this issue because there were conflicting layering issues. 
this pr re-works how we set the navigation bar to `fixed` by ignoring the inView and using the window.scrollY to identify when we should set it
=> reworked nav bar

components/blocks/Features.tsx, content/blog/Improving-TinaCloud-Indexing-with-Native-Git-CLI-and-Sparse-Checkout.md
As per @adamcogan's email 
**Tina.io - Code snippets should be black like VSCode**
1. See red arrow - Code snippet background should be black like VSCode
So change from the dark blue (ugly) to black
2. Any other ones to fix
This PR changes the colour of the codeblock backgrounds from a navy-blue gradient to a gray-black gradient 
_note test passed by @bettybondoc_
=> 💄Code-block colour change 

components/layout/Footer.tsx
As per #1817 we have marginally increased the right padding of the footer so that the tinaGPT does not overlap with the footer text .
**Figure: After padding shift**
=> 🐛 TInaGPT covering footer text

components/forms/BookDemo.tsx
The last PR which went through added a modal for users to opt who they want to speak to.
- There was a mistake which specified there were only 2 columns instead of 3 - this fixes that
=> ❗fix column number

content/docs/reference/media/repo-based.md
This pull request updates the TinaCMS documentation to clarify the behavior of the static property within the media configuration object in config.ts.
A new section has been added to explain the purpose and impact of the static property.
The explanation details how static: true makes media files static assets (uneditable through TinaCMS) and static: false (default) allows editors to upload, edit, and delete media directly within the editor.
=> Docs: Explain `static` property for media configuration

components/blocks/CompareBox.tsx
As per https://github.com/tinacms/tina.io/issues/1875 we wanted to decrease spacing between the company logos on the comparison box slider. To do so, i have increased the amount of logos we show on the XL view (i.e dev mode laptop L + view) 
**Figure: 💄Before Fix - Company Logos Spacing**
**Figure: 💄After Fix - Company Logos Spacing**
=> 💄Decrease Logo Spacing

content/blog/a-b-test-with-tina.md, content/examples/index.json
=> Docs - change from `Tailwind starter` to `Next.js Starter`

content/docs/errors/faq.md
Users have reported issues arising from GitHub branch protection rules being enforced. This change adds a section regarding document saving issues, with general guidance on how to resolve them.
Issue 2108 has been raised separately on Tina Cloud to fix the error message displayed.
=> Adds 'Problem saving your document' section to FAQ

.gitignore, scripts/content-auditor/README.md, scripts/content-auditor/content-auditor-prompt.txt, scripts/content-auditor/content-auditor.py
To efficiently work through the large amount of content on the Tina docs pages, I've added a Python3 content audit script that uses local AI to analyze each page with a variable prompt, and I've included a readme file for usage.
The implementation leverages [ollama](https://ollama.com/) as the local LLM server of choice – making an HTTP request for each separate file.
The URL can be swapped out and payload modified to use other local LLM servers, or other APIs that may have better results or a larger parameter size.
The script generates two files, one that contains a list of all discovered markdown content. 
The other, `auditor-responses.md` contains each file and marks it as either "clean" or with the prompt response text. 
To get the filter effect (marking files as clean), the prompt …
=> 🤖 New Script – AI Automated Content Audit

components/ui/DocsPagination.tsx, content/docs/extending-tina/validation.mdx, pages/blog/[slug].tsx, pages/docs/product-tour.tsx
As per https://github.com/tinacms/tina.io/issues/1929 this PR addresses the UI of the docs pagination
**Figure: ❌ Current - NEXT is over entire page**
**Figure: ✅ Test passed by @bettybondoc - NEXT is only on the right**
=> 💄UI docs pagination

pages/blog/[slug].tsx
Headings were getting cut off as they were split into children and only the first was being taken in some cases, changed to include all children.
*Figure 1 – bugged headings*
*Figure 2 – post fix*
=> 🐞 Headings cut off prematurely, small change so they render properly again

components/blocks/Pricing.tsx
Stemming from #2071, we've just bumped up the size of the text in the includes section for mobile view 
**Figure: Updated View**
=> 💄Increase size of text for mobile

.prettierrc, components/blocks/IconSelector.tsx
As per https://github.com/tinacms/tina.io/issues/2086 i have refactored the icon selector component to have
1. a drop down,
2. displaying the icons nexto the names and 
3. removing the prefix (i.e 'Fa') 
**Figure: Click 'Show Icons'**
**Figure: New Icon Selector**
=> ♻️ Refactor Icon Selector Component

.editorconfig, .github/workflows/dispatch-create-whats-new-page.yml, scripts/create-release-notes.sh
Intent is to get TinaCMS and TinaCloud repos to call this workflow when pushing new releases to production.
Workflow also opens a new PR (with automerge). Once this is known to be stable - rules can be relaxed for these PRs
scripts/create-release-notes.sh - creates the file in the same format as the existing release notes
=> workflow - added a workflow to create a what's new page

.github/workflows/dispatch-create-whats-new-page.yml, content/whats-new-tinacloud/2024.09.22.mdx
Based off the logs from https://github.com/tinacms/tina.io/actions/runs/10893065830/job/30227231474 - the release notes were being used to generate the branch name
This PR uses the version number in the branch name and should alleviate the issue
=> dispatch-create-whats-new-page - fix branch name

components/tinaMarkdownComponents/docAndBlogComponents.tsx
There was a bit of styling that was interfering with the titles in doc bodies. See Screenshots below.
Removed the flex styling and made the link portion (only) with flex properties. Added some bottom margin to raise it up as well.
**From (bugged)**
**To (with fix)**
<details>
</details>
=> 🐛 Docs Title Styling Fix – Code Blocks

package.json, pages/api/graphql.ts, pnpm-lock.yaml
This is kind of interesting – Jeff mentioned the existence of a Tina playground and we thought nobody had access to it anymore / was using it.
It's not something we include on the site afaik.
Removing this package seems to have broken it – can be found at https://tina-gql-playground.vercel.app/object-list-templates.
=> Revert "➖ Old Dependencies – Removing @tinacms/graphql-old and /datalayer-old"

pages/whats-new/tinacms.tsx
As per https://github.com/tinacms/tina.io/issues/2194 I have addressed the mobile ui of the /whats-new/tinacms page.
Prior, it seemed that mx-auto was setting a margin for the smaller screens and therefore we had a gutter of white. I have restricted this to only medium+ screens using tailwind. 
Tssted on iPhone 15 Safari ✅
**Figure: iPhone 15 Test**
=> 🐛 /whats-new/tinacms mobile ui fix layout bug 

content/docs/introduction/faq.mdx
=> 📄 FAQ - Update Base Path

components/ui/BlogPagination.tsx
Whilst attempting to upgrade the remark dependency i found a legacyBehaviour issue with anchor tags being passed into the `DynamicLink` component. So i've removed the anchors and replaced them with span tags 
[⬆ Updating Dependencies – Remark](https://github.com/tinacms/tina.io/issues/2214)
=> remove <a/> from passing into Link

components/blocks/CarouselFeature.tsx
Refactors the carousel component to use NextJS' image component, which will permit the use of intermediate caching for GIFs and defer content loading until image is visible
=> ♻️ Refactor carousel to use NextJS' Image component

components/DocumentationNavigation/DocsNavigationList.tsx
As per https://github.com/tinacms/tina.io/issues/2244 this is a simple PR removing the tree dots nexto highlighted items in the Tina Docs 
**Figure: Updated Docs ToC**
=> 💄 ToC Cleanup 

next.config.js, vercel.json
This PR is to address [#24](https://github.com/tinacms/business-backlog/issues/24)
Essentially we were seeing in our SEMRush audits that we had a series of long redirect chains. However they were primarily because we were using the 'trailingSlash: true' which saw redirects that did not have an appended final '/' having added them.
i.e if we re-routed a user to `/legacy-redirect`, our config was then re-routing to `/legacy-redirect/`
Adding this extra forward slash was increasing this chain. 
@landonmaxwell tested this branch on SEMRush and found that this fixed the issue o redirect chains and loops
**Figure: Long Redirect chains eliminated**
=> SEO & Redirects - Remove Trailing Slash and Fix Redirects

content/docs/forestry/media.mdx
As per [🖼️ Broken image link - Migrating from Forestry Docs](https://github.com/tinacms/tina.io/issues/2383) fixes media
**Figure: Media being served in preview**
=> 🌠 Fix Lost Media

components/blocks/CarouselFeature.tsx
As per #2406 
The tasks 
**Figure 1: Equal X padding on mobile**
**Figure 2: Headline, body and button alligned in mobile**
**Figure 3: Cards in laptop view - all items alligned**
=> 🐛 UI fixes to Key Features Component 

components/blocks/CarouselFeature.tsx
As per #2406 
The tasks 
**Figure 1: Equal X padding on mobile**
**Figure 2: Headline, body and button alligned in mobile**
**Figure 3: Cards in laptop view - all items alligned**
=> 🐛 key features - spacing and sizing fixes

components/DocumentationNavigation/DocsNavigationList.tsx
As per https://github.com/tinacms/tina.io/issues/2403 
I investigated as to why the highlighting wasnt working - through a series of logs i found it was because one of the conditions of a nav item being highlighted was `!categoryData.items && !selected`. 
Upon further looking it turns out that the `selected` boolean wasnt being set correctly due to a trailing back slash. 
This would be due to the removal of automatic trailing backslashes made last week as we aimed to reduce our redirect chains (see https://github.com/tinacms/tina.io/pull/2399 for more context) 
This PR just removes the trailing backslash at the end of the `slug` var using regex
=> 🌠 Fix docs highlighting 

components/DocumentationNavigation/DocsLeftSidebar.tsx
tiny pr fix for #2452 dropping the z-index of the left hand navigation menu 
**Changes**
- removed duplicate z-index css 
- dropped z-index below nav bar hover item z-index (49 -> 39)
=> drop z-index for lefthand nav

content/blocksPages/home.json, content/blog/Click-to-Edit-Comes-to-Visual-Editing.mdx, content/docs/contextual-editing/react.mdx, content/docs/contextual-editing/tinafield.mdx
For https://github.com/tinacms/quick-edit-demo/issues/11 we created a subdomain `demo.tina.io` to make the site more integrated to our tina.io. 
This PR just changes all url references on tina.io from `quick-edit-demo.vercel.app` to `demo.tina.io`
**Figure: Vercel Domains - Old Domain Redirects to New (301)**
=> 🔌 Change DEMO Url

components/tinaMarkdownComponents/docAndBlogComponents.tsx
As per #2506
- Issue was occurring on safari (instead of chromium browsers) 
- safari wasnt recognising `text-decoration: underline rgba(0, 0, 0, 0.3);` in css sheet 
- added explicit markdown styling for <a/> tags
**Figure: Safari underlined links fixed**
=> add explicit markdown styling for anchor tags

components/blocks/FeatureCarousel/CarouselFeature.tsx
Video's have been made to play-inline, preload less and make source tags more explicit. Which seems to stop a constant refresh issue as described in #2589.
Trying to use an invalid file type will throw an error now too...
=> Attempted Fix for Safari Issues

content/docs/frameworks/next/app-router.mdx, content/docs/frameworks/next/pages-router.mdx
As per https://github.com/tinacms/tina.io/issues/2586 - fixing the internal linking to the TinaCMS content modelling docs
=> 🐛 Fix Doc Broken Links

components/docsSearch/SearchComponent.tsx, components/docsSearch/SearchNavigation.tsx, utils/new-search.tsx
As per #2551 we want to be able to see highlighting in our search hits. This was an awesome feature of the old docs searching that we still need to reimplement into the new style of search
Added a helper function which, when passed through the newly included `item._highlightResult` will regex match to format hits accordingly 
**Figure: Highlighting Search Results**
**Figure: Highlight search results on /search**
=> ✨ Add Search Highlighting

components/layout/setup-overview.tsx
The docs experience wasnt great because i couldnt use the pagination from the beginning. This has been fixed by adding the `<DocsPagination/>` component to the /setup-overview page
=> Added Docs Pagination to Setup-Overview

components/layout/DocsLayout.tsx
From adam's email...
1. See image – Left Nav when you go to the bottom, there should still be a little bit of white space before the orange footer
**Figure – Before change**
**Figure – After change**
=> 💄 Docs – Adding some padding to the bottom of the layout grid

pages/docs/[...slug].tsx
As per #2668 some of the docs pages that havent been updated were displaying a last edited date of January 1970. This is because the date was null and it was being parsed into a default date with `Date`.
To combat this i've hidden dates if they are null
=> 📑 docs - hide date if it is null

pages/_document.tsx
As per https://github.com/tinacms/tina.io/issues/2636 added lang tag to _document.tsx because language doesnt change on tina.io / we do not support multi-lingual
=> added lang tag to _document.tsx

content/docs/reference/toolkit/fields/blocks.mdx, utils/shortcodes.tsx
cc: @isaaclombardssw  
As per https://github.com/tinacms/tina.io/issues/2701 all i've done is added a warning callout and fixed the padding with a `className='py-2'` 
**Figure: Updated UI**
=> Add Out-Dated Warning + Fix Styling of Warning Callout

components/layout/Footer.tsx
As per #2695, this PR ensures that we do not create a mega menu in our footer by only allowing for one LinkGroup to be open at any one time
=> 💄 Avoid Mega-Menu in Footer

components/blocks/RecentPosts/RecentPosts.tsx
Fixed the styling of the Recent Posts block - aswell as removing styled jsx. As per [🐛 UI Issue on Homepage | Recent Posts](https://github.com/tinacms/tina.io/issues/2798)
**Figure: Fixed UI**
**Figure: Old bugged UI**
=> 🐛 fix recent posts styling and remove styled jsx

components/tinaMarkdownComponents/docAndBlogComponents.tsx
Prompted from email (see below)
For #2811 
Added button (UI from ShadCN - https://github.com/shadcn-ui/ui/blob/main/apps/www/components/copy-button.tsx) to the prismjs docs 
Uploading Screen Recording 2025-01-29 at 5.49.31 pm.mov…
**Figure: Screen Recording - Copy!**
-------
From Dan M
Hey Nick,
I’m catching up on some of my CTFs and am doing an older TinaCMS one today. Seeing as this CTF was done ages ago, I’m sending my feedback via email.
When following a starter, there are commands I need to run in a terminal. Normally I would expect there to be a ‘copy’ widget that allows me to easy copy and paste commands between the browser and terminal. However, in the TinaCMS docs this seems to be missing.
Please add a ‘copy’ feature to all code snippets throughout the site
=> ✨ added copy button to the prism code block for docs

app/blog/[...slug]/page.tsx, app/docs/[...slug]/page.tsx, content/blog/tinacms-ui-whats-next.mdx, content/docs/index.mdx, content/siteConfig.json
This PR seeks to improve the SEO of the tina.io site by having unique fallback SEO descriptions primarily for the docs and blogs.
It also removes 2 old references that are not available currently 
**Figure: Pre-Change SEO**
**Figure: Post-change SEO**
=> Addressing seo issues

components/AppRouterMigrationComponents/Docs/docsSearch/SearchNavigation.tsx
As per https://github.com/tinacms/tina.io/issues/2790
I have dropped the height of the `LeftHandSideParentContainer` so that it doesnt hug the bottom of the page when the user is scrolling down the page. See video 
https://github.com/user-attachments/assets/f5760a5c-5846-454e-9b0f-db53aba68672
**Figure: Left hand bar doesnt hug bottom anymore**
=> 🐛 drop height of left-hand-container to fix scroll height 

components/AppRouterMigrationComponents/AppNavBar.tsx, components/blocks/Container.tsx, components/blocks/RecentPosts/RecentPosts.tsx, components/ui/Button.tsx
As per https://github.com/tinacms/tina.io/issues/2781 i investigated why the white strip on the iPhone was appearing - it seemed it was from 2 things: 
1. The navbar buttons were too large and causing an x-overflow
2. the RecentPosts section was w-full and then adding padding ontop
**Fixes:**
1. added an extraSmall class for the navbar buttons, this allowed us to drop the size of the buttons without impacting other components on the site 
2. dropped w-full and introduced specific padding for the recentPosts section 
**Figure: navbar fits on mobile now**
**Figure: RecentPosts fits on mobile now**
=> 🐛Fix iphone white strip

components/layout/Footer.tsx
Removed CSS class to make Social links column be 50% width
Closes https://github.com/tinacms/tina.io/issues/2827
=> Update Footer.tsx to fix social icons on mobile

content/docs/graphql/queries/get-document.mdx
Add example for reference reference query
=> feat: reverse references example

app/conference/ConferenceClient.tsx, content/conference/TinaCon2025.mdx
As per adams request, the big change in this PR is to make the agenda section a singular 2d table so users can view all items occurring at once 
**Figure: > Md view**
**Figure: < Md view**
=> Rework Agenda Section

components/AppRouterMigrationComponents/AdminLink.tsx, components/AppRouterMigrationComponents/AppNavBar.tsx
cc: @micsblank 
As per https://github.com/tinacms/tina.io/issues/2759 we have made a few minor changes
**Figure: Before**
**Figure: After**
=> Fix MdMenu Pullout Location 

app/docs/[...slug]/docs-client.tsx, app/zh/docs/[...slug]/docs-client.tsx, components/AppRouterMigrationComponents/Docs/toc/index.tsx
As per [💄Docs UX - Unusual Highlighting in RHS Table of Contents on Docs](https://github.com/tinacms/tina.io/issues/3080) 
**Before**
**After**
=> RHS ToC - only one active item

app/layout.tsx
On [tina.io](https://tina.io/), in Devtools | Network, the global.css and tailwind.css are 404'ing - see **figure** below.
The preload links were trying to fetch /styles/tailwind.css and /app/global.css as static assets.
These files don't exist at those URL paths because they're CSS modules that should be imported, not served as static files.
Next.js handles CSS imports automatically through the import statements, so the preload links were unnecessary and causing 404 errors.
✅ It's now fixed - see **figure** below.
**Figure: global.css and tailwind.css are 404'ing**
**Figure: global.css and tailwind.css are fixed**
=> 🐛 Fixed 404 on global.css and tailwind.css

app/api/githubstar/route.ts
There was an error locally where githubstar was causing a 500 error - see **figure** below
The 500 error occurred because the GitHub star API route required GITHUB_STAR_TOKEN, which wasn’t set locally. Without it, the GitHub request failed and returned 500.
Updated app/api/githubstar/route.ts to make the token optional:
- If GITHUB_STAR_TOKEN is set, use it (higher rate limit).
- If not, make unauthenticated requests (60/hour).
That fixed the 500 - see **figure** below
**Figure: 500 error locally due to githubstar** 
**Figure: No more 500**
=> 🐛 Fixed 500 error on githubstar fetch
